// Classification of every VS Code workbench color key onto the 2-bit
// design system. Hand-tune freely — this file is the source of truth.
// Sync against a new VS Code version with `npm run extract-color-keys`
// followed by `npm run sync-classification` (existing roles are kept).
// `null` means deliberately unset (VS Code default/derived value is fine).
import { TokenName } from './theme';

export const workbenchClassification: Record<string, TokenName | null> = {
    // actionBar
    'actionBar.toggledBackground': 'selectionBg',
    // activeSessionView
    'activeSessionView.background': 'bgBase',
    'activeSessionView.foreground': 'fgPrimary',
    // activityBar
    'activityBar.activeBackground': 'selectionBgStrong',
    'activityBar.activeBorder': 'borderFocus',
    'activityBar.activeFocusBorder': 'borderFocus',
    'activityBar.background': 'bgSunken',
    'activityBar.border': 'borderSubtle',
    'activityBar.dropBorder': 'borderSubtle',
    'activityBar.foreground': 'fgPrimary',
    'activityBar.inactiveForeground': 'fgMuted',
    // activityBarBadge
    'activityBarBadge.background': 'invertBg',
    'activityBarBadge.foreground': 'invertFg',
    // activityBarTop
    'activityBarTop.activeBackground': 'selectionBgStrong',
    'activityBarTop.activeBorder': 'borderFocus',
    'activityBarTop.background': 'bgBase',
    'activityBarTop.dropBorder': 'borderSubtle',
    'activityBarTop.foreground': 'fgSecondary',
    'activityBarTop.inactiveForeground': 'fgMuted',
    // activityErrorBadge
    'activityErrorBadge.background': 'invertBg',
    'activityErrorBadge.foreground': 'invertFg',
    // activityWarningBadge
    'activityWarningBadge.background': 'invertBg',
    'activityWarningBadge.foreground': 'invertFg',
    // agentFeedbackEditorWidget
    'agentFeedbackEditorWidget.background': 'bgWidget',
    'agentFeedbackEditorWidget.border': 'borderSubtle',
    // agentFeedbackInputWidget
    'agentFeedbackInputWidget.border': 'borderSubtle',
    // agentSessionReadIndicator
    'agentSessionReadIndicator.foreground': 'fgSecondary',
    // agentSessionSelectedBadge
    'agentSessionSelectedBadge.border': 'borderSubtle',
    // agentSessionSelectedUnfocusedBadge
    'agentSessionSelectedUnfocusedBadge.border': 'borderSubtle',
    // agentStatusIndicator
    'agentStatusIndicator.background': 'bgBase',
    // agents
    'agents.background': 'bgBase',
    // agentsBadge
    'agentsBadge.background': 'invertBg',
    'agentsBadge.foreground': 'invertFg',
    // agentsChatInput
    'agentsChatInput.background': 'bgBase',
    'agentsChatInput.border': 'borderSubtle',
    'agentsChatInput.focusBorder': 'borderFocus',
    'agentsChatInput.foreground': 'fgSecondary',
    'agentsChatInput.placeholderForeground': 'fgMuted',
    // agentsGradient
    'agentsGradient.tintColor': 'fgTertiary',
    // agentsNewSessionButton
    'agentsNewSessionButton.background': 'bgBase',
    'agentsNewSessionButton.border': 'borderSubtle',
    'agentsNewSessionButton.foreground': 'fgSecondary',
    'agentsNewSessionButton.hoverBackground': 'bgRaised',
    // agentsPanel
    'agentsPanel.background': 'bgBase',
    'agentsPanel.border': 'borderSubtle',
    'agentsPanel.foreground': 'fgSecondary',
    // agentsUnreadBadge
    'agentsUnreadBadge.background': 'invertBg',
    'agentsUnreadBadge.foreground': 'invertFg',
    // agentsUpdateButton
    'agentsUpdateButton.downloadedBackground': 'bgBase',
    'agentsUpdateButton.downloadingBackground': 'bgBase',
    // agentsVoice
    'agentsVoice.speakingBackground': 'bgBase',
    'agentsVoice.speakingForeground': 'fgSecondary',
    // badge
    'badge.background': 'invertBg',
    'badge.foreground': 'invertFg',
    // banner
    'banner.background': 'invertBg',
    'banner.foreground': 'invertFg',
    'banner.iconForeground': 'invertFg',
    // breadcrumb
    'breadcrumb.activeSelectionForeground': 'fgPrimary',
    'breadcrumb.background': 'bgBase',
    'breadcrumb.focusForeground': 'fgPrimary',
    'breadcrumb.foreground': 'fgMuted',
    // breadcrumbPicker
    'breadcrumbPicker.background': 'bgWidget',
    // browser
    'browser.border': 'borderSubtle',
    // button
    'button.background': 'invertBgMuted',
    'button.border': null,
    'button.foreground': 'invertFg',
    'button.hoverBackground': 'invertBg', // buttons rest one rung down and light up
    'button.secondaryBackground': 'bgBase',
    'button.secondaryBorder': 'borderSubtle',
    'button.secondaryForeground': 'fgPrimary',
    'button.secondaryHoverBackground': 'bgWidget',
    'button.separator': 'invertFg',
    // chart
    'chart.axis': 'fgTertiary',
    'chart.guide': 'fgTertiary',
    'chart.line': 'fgTertiary',
    // charts
    'charts.blue': 'fgSecondary',
    'charts.foreground': 'fgSecondary',
    'charts.green': 'fgTertiary',
    'charts.lines': 'fgMuted',
    'charts.orange': 'fgSecondary',
    'charts.purple': 'fgTertiary',
    'charts.red': 'fgPrimary',
    'charts.yellow': 'fgSecondary',
    // chat
    'chat.avatarBackground': 'bgWidget',
    'chat.avatarForeground': 'fgSecondary',
    'chat.checkpointSeparator': 'fgTertiary',
    'chat.editedFileForeground': 'fgSecondary',
    'chat.inputWorkingBorderColor1': 'alphaMid', // must be translucent
    'chat.inputWorkingBorderColor2': 'alphaMid', // must be translucent
    'chat.inputWorkingBorderColor3': 'alphaMid', // must be translucent
    'chat.linesAddedForeground': 'alphaText', // must be translucent (keeps monochrome vs. default green)
    'chat.linesRemovedForeground': 'alphaText', // must be translucent (keeps monochrome vs. default red)
    'chat.requestBackground': 'bgWidget',
    'chat.requestBorder': 'borderSubtle',
    'chat.requestBubbleBackground': 'alphaFaint', // must be translucent
    'chat.requestBubbleHoverBackground': 'alphaMid', // must be translucent
    'chat.requestCodeBorder': 'alphaMid', // must be translucent
    'chat.slashCommandBackground': 'bgWidget',
    'chat.slashCommandForeground': 'fgSecondary',
    'chat.thinkingShimmer': 'alphaStrong', // must be translucent (shimmer effect)
    // checkbox
    'checkbox.background': 'bgSunken',
    'checkbox.border': 'borderSubtle',
    'checkbox.disabled.background': 'bgBase',
    'checkbox.disabled.foreground': 'fgMuted',
    'checkbox.foreground': 'fgPrimary',
    'checkbox.selectBackground': 'bgBase',
    'checkbox.selectBorder': 'borderSubtle',
    // commandCenter
    'commandCenter.activeBackground': 'selectionBg',
    'commandCenter.activeBorder': 'borderFocus',
    'commandCenter.activeForeground': 'fgPrimary',
    'commandCenter.background': 'bgBase',
    'commandCenter.border': 'borderSubtle',
    'commandCenter.debuggingBackground': 'alphaFaint', // must be translucent
    'commandCenter.foreground': 'fgSecondary',
    'commandCenter.inactiveBorder': 'alphaMid',
    'commandCenter.inactiveForeground': 'fgMuted',
    // commentsView
    'commentsView.resolvedIcon': 'fgSecondary',
    'commentsView.unresolvedIcon': 'fgSecondary',
    // contrastActiveBorder
    'contrastActiveBorder': null,
    // contrastBorder
    'contrastBorder': null,
    // debugConsole
    'debugConsole.errorForeground': 'fgPrimary',
    'debugConsole.infoForeground': 'fgTertiary',
    'debugConsole.sourceForeground': 'fgSecondary',
    'debugConsole.warningForeground': 'fgSecondary',
    // debugConsoleInputIcon
    'debugConsoleInputIcon.foreground': 'fgSecondary',
    // debugExceptionWidget
    'debugExceptionWidget.background': 'bgWidget',
    'debugExceptionWidget.border': 'borderFocus',
    // debugIcon
    'debugIcon.breakpointCurrentStackframeForeground': 'fgSecondary',
    'debugIcon.breakpointDisabledForeground': 'fgMuted',
    'debugIcon.breakpointForeground': 'fgSecondary',
    'debugIcon.breakpointStackframeForeground': 'fgSecondary',
    'debugIcon.breakpointUnverifiedForeground': 'fgSecondary',
    'debugIcon.continueForeground': 'fgSecondary',
    'debugIcon.disconnectForeground': 'fgSecondary',
    'debugIcon.pauseForeground': 'fgSecondary',
    'debugIcon.restartForeground': 'fgSecondary',
    'debugIcon.startForeground': 'fgSecondary',
    'debugIcon.stepBackForeground': 'fgSecondary',
    'debugIcon.stepIntoForeground': 'fgSecondary',
    'debugIcon.stepOutForeground': 'fgSecondary',
    'debugIcon.stepOverForeground': 'fgSecondary',
    'debugIcon.stopForeground': 'fgSecondary',
    // debugTokenExpression
    'debugTokenExpression.boolean': 'fgTertiary',
    'debugTokenExpression.error': 'fgTertiary',
    'debugTokenExpression.name': 'fgTertiary',
    'debugTokenExpression.number': 'fgTertiary',
    'debugTokenExpression.string': 'fgTertiary',
    'debugTokenExpression.type': 'fgTertiary',
    'debugTokenExpression.value': 'fgTertiary',
    // debugToolBar
    'debugToolBar.background': 'bgWidget',
    'debugToolBar.border': 'borderSubtle',
    // debugView
    'debugView.exceptionLabelBackground': 'bgBase',
    'debugView.exceptionLabelForeground': 'fgSecondary',
    'debugView.stateLabelBackground': 'bgBase',
    'debugView.stateLabelForeground': 'fgSecondary',
    'debugView.valueChangedHighlight': 'fgTertiary',
    // descriptionForeground
    'descriptionForeground': 'fgMuted',
    // diffEditor
    'diffEditor.border': 'borderSubtle',
    'diffEditor.diagonalFill': 'borderSubtle',
    'diffEditor.insertedLineBackground': 'alphaFaint',
    'diffEditor.insertedTextBackground': 'alphaFaint',
    'diffEditor.insertedTextBorder': null,
    'diffEditor.move.border': 'borderSubtle',
    'diffEditor.moveActive.border': 'borderSubtle',
    'diffEditor.removedLineBackground': 'alphaMid',
    'diffEditor.removedTextBackground': 'alphaMid',
    'diffEditor.removedTextBorder': null,
    'diffEditor.unchangedCodeBackground': 'bgBase',
    'diffEditor.unchangedRegionBackground': 'bgBase',
    'diffEditor.unchangedRegionForeground': 'fgSecondary',
    'diffEditor.unchangedRegionShadow': 'shadow',
    // diffEditorGutter
    'diffEditorGutter.insertedLineBackground': 'bgBase',
    'diffEditorGutter.removedLineBackground': 'bgBase',
    // diffEditorOverview
    'diffEditorOverview.insertedForeground': 'fgSecondary',
    'diffEditorOverview.removedForeground': 'fgSecondary',
    // disabledForeground
    'disabledForeground': 'fgMuted',
    // dropdown
    'dropdown.background': 'bgWidget',
    'dropdown.border': 'borderSubtle',
    'dropdown.foreground': 'fgPrimary',
    'dropdown.listBackground': 'bgWidget',
    // editor
    'editor.background': 'bgBase',
    'editor.compositionBorder': 'borderSubtle',
    'editor.findMatchBackground': 'alphaStrong',
    'editor.findMatchBorder': 'borderFocus',
    'editor.findMatchForeground': 'fgSecondary',
    'editor.findMatchHighlightBackground': 'alphaMid',
    'editor.findMatchHighlightBorder': null,
    'editor.findMatchHighlightForeground': null, // must be translucent; unset falls back to monochrome fg
    'editor.findRangeHighlightBackground': 'alphaFaint',
    'editor.findRangeHighlightBorder': 'alphaMid', // must be translucent
    'editor.focusedStackFrameHighlightBackground': 'alphaStrong',
    'editor.foldBackground': 'alphaFaint',
    'editor.foldPlaceholderForeground': 'fgMuted',
    'editor.foreground': 'fgPrimary',
    'editor.hoverHighlightBackground': 'alphaMid',
    'editor.inactiveLineHighlightBackground': 'alphaMid',
    'editor.inactiveSelectionBackground': 'alphaMid',
    'editor.inlineValuesBackground': 'bgBase',
    'editor.inlineValuesForeground': 'fgSecondary',
    'editor.lineHighlightBackground': 'alphaMid',
    'editor.lineHighlightBorder': 'transparent',
    'editor.linkedEditingBackground': 'alphaFaint',
    'editor.placeholder.foreground': 'fgMuted',
    'editor.rangeHighlightBackground': 'alphaFaint',
    'editor.rangeHighlightBorder': 'borderSubtle',
    'editor.selectionBackground': 'selectionBg',
    'editor.selectionForeground': 'fgPrimary',
    'editor.selectionHighlightBackground': 'alphaFaint',
    'editor.selectionHighlightBorder': null,
    'editor.snippetFinalTabstopHighlightBackground': 'alphaMid',
    'editor.snippetFinalTabstopHighlightBorder': 'borderSubtle',
    'editor.snippetTabstopHighlightBackground': 'alphaMid',
    'editor.snippetTabstopHighlightBorder': 'borderSubtle',
    'editor.stackFrameHighlightBackground': 'alphaMid',
    'editor.symbolHighlightBackground': 'alphaMid',
    'editor.symbolHighlightBorder': 'borderSubtle',
    'editor.wordHighlightBackground': 'alphaFaint',
    'editor.wordHighlightBorder': 'borderSubtle',
    'editor.wordHighlightStrongBackground': 'alphaMid',
    'editor.wordHighlightStrongBorder': 'borderSubtle',
    'editor.wordHighlightTextBackground': 'alphaFaint',
    'editor.wordHighlightTextBorder': 'borderSubtle',
    // editorActionList
    'editorActionList.background': 'bgBase',
    'editorActionList.focusBackground': 'selectionBg',
    'editorActionList.focusForeground': 'fgPrimary',
    'editorActionList.foreground': 'fgSecondary',
    // editorActiveLineNumber
    'editorActiveLineNumber.foreground': 'fgMuted', // legacy alias of editorLineNumber.activeForeground; keep them equal // deprecated -> editorLineNumber.activeForeground
    // editorBracketHighlight
    'editorBracketHighlight.foreground1': 'fgMuted',
    'editorBracketHighlight.foreground2': 'fgMuted',
    'editorBracketHighlight.foreground3': 'fgMuted',
    'editorBracketHighlight.foreground4': 'fgMuted',
    'editorBracketHighlight.foreground5': 'fgMuted',
    'editorBracketHighlight.foreground6': 'fgMuted',
    'editorBracketHighlight.unexpectedBracket.foreground': 'fgPrimary',
    // editorBracketMatch
    'editorBracketMatch.background': 'alphaFaint',
    'editorBracketMatch.border': 'borderSubtle',
    'editorBracketMatch.foreground': 'fgSecondary',
    // editorBracketPairGuide
    'editorBracketPairGuide.activeBackground1': 'fgMuted',
    'editorBracketPairGuide.activeBackground2': 'fgMuted',
    'editorBracketPairGuide.activeBackground3': 'fgMuted',
    'editorBracketPairGuide.activeBackground4': 'fgMuted',
    'editorBracketPairGuide.activeBackground5': 'fgMuted',
    'editorBracketPairGuide.activeBackground6': 'fgMuted',
    'editorBracketPairGuide.background1': 'alphaStrong',
    'editorBracketPairGuide.background2': 'alphaStrong',
    'editorBracketPairGuide.background3': 'alphaStrong',
    'editorBracketPairGuide.background4': 'alphaStrong',
    'editorBracketPairGuide.background5': 'alphaStrong',
    'editorBracketPairGuide.background6': 'alphaStrong',
    // editorCodeLens
    'editorCodeLens.foreground': 'fgMuted',
    // editorCommentsWidget
    'editorCommentsWidget.rangeActiveBackground': 'alphaMid',
    'editorCommentsWidget.rangeBackground': 'alphaMid',
    'editorCommentsWidget.replyInputBackground': 'bgWidget',
    'editorCommentsWidget.resolvedBorder': 'borderSubtle',
    'editorCommentsWidget.unresolvedBorder': 'borderSubtle',
    // editorCursor
    'editorCursor.background': 'bgBase',
    'editorCursor.foreground': 'fgPrimary',
    // editorError
    'editorError.background': null,
    'editorError.border': null,
    'editorError.foreground': 'fgPrimary',
    // editorGhostText
    'editorGhostText.background': null,
    'editorGhostText.border': null,
    'editorGhostText.foreground': 'fgMuted',
    // editorGroup
    'editorGroup.border': 'borderSubtle',
    'editorGroup.dropBackground': 'alphaMid',
    'editorGroup.dropIntoPromptBackground': 'alphaMid',
    'editorGroup.dropIntoPromptBorder': 'borderSubtle',
    'editorGroup.dropIntoPromptForeground': 'fgSecondary',
    'editorGroup.emptyBackground': 'bgSunken',
    'editorGroup.focusedEmptyBorder': 'borderSubtle',
    // editorGroupHeader
    'editorGroupHeader.border': null,
    'editorGroupHeader.noTabsBackground': 'bgBase',
    'editorGroupHeader.tabsBackground': 'bgSunken',
    'editorGroupHeader.tabsBorder': 'borderSubtle',
    // editorGutter
    'editorGutter.addedBackground': 'fgMuted',
    'editorGutter.addedSecondaryBackground': 'alphaFaint',
    'editorGutter.background': 'bgBase',
    'editorGutter.commentDraftGlyphForeground': 'fgSecondary',
    'editorGutter.commentGlyphForeground': 'fgSecondary',
    'editorGutter.commentRangeForeground': 'fgMuted',
    'editorGutter.commentUnresolvedGlyphForeground': 'fgSecondary',
    'editorGutter.deletedBackground': 'fgPrimary',
    'editorGutter.deletedSecondaryBackground': 'alphaStrong',
    'editorGutter.foldingControlForeground': 'fgMuted',
    'editorGutter.itemBackground': 'bgBase',
    'editorGutter.itemGlyphForeground': 'fgSecondary',
    'editorGutter.modifiedBackground': 'fgTertiary',
    'editorGutter.modifiedSecondaryBackground': 'alphaMid',
    // editorHint
    'editorHint.border': null,
    'editorHint.foreground': 'fgMuted',
    // editorHoverWidget
    'editorHoverWidget.background': 'bgWidget',
    'editorHoverWidget.border': 'borderSubtle',
    'editorHoverWidget.foreground': 'fgSecondary',
    'editorHoverWidget.highlightForeground': 'fgPrimary',
    'editorHoverWidget.statusBarBackground': 'bgBase',
    // editorIndentGuide
    'editorIndentGuide.activeBackground': null, // deprecated -> editorIndentGuide.activeBackground1
    'editorIndentGuide.activeBackground1': 'fgMuted',
    'editorIndentGuide.activeBackground2': 'fgMuted',
    'editorIndentGuide.activeBackground3': 'fgMuted',
    'editorIndentGuide.activeBackground4': 'fgMuted',
    'editorIndentGuide.activeBackground5': 'fgMuted',
    'editorIndentGuide.activeBackground6': 'fgMuted',
    'editorIndentGuide.background': null, // deprecated -> editorIndentGuide.background1
    'editorIndentGuide.background1': 'alphaStrong',
    'editorIndentGuide.background2': 'alphaStrong',
    'editorIndentGuide.background3': 'alphaStrong',
    'editorIndentGuide.background4': 'alphaStrong',
    'editorIndentGuide.background5': 'alphaStrong',
    'editorIndentGuide.background6': 'alphaStrong',
    // editorInfo
    'editorInfo.background': null,
    'editorInfo.border': null,
    'editorInfo.foreground': 'fgTertiary',
    // editorInlayHint
    'editorInlayHint.background': 'bgRaised',
    'editorInlayHint.foreground': 'fgSecondary',
    'editorInlayHint.parameterBackground': 'bgRaised',
    'editorInlayHint.parameterForeground': 'fgSecondary',
    'editorInlayHint.typeBackground': 'bgRaised',
    'editorInlayHint.typeForeground': 'fgSecondary',
    // editorLightBulb
    'editorLightBulb.foreground': 'fgSecondary',
    // editorLightBulbAi
    'editorLightBulbAi.foreground': 'fgSecondary',
    // editorLightBulbAutoFix
    'editorLightBulbAutoFix.foreground': 'fgSecondary',
    // editorLineNumber
    'editorLineNumber.activeForeground': 'fgMuted',
    'editorLineNumber.dimmedForeground': 'alphaMid',
    'editorLineNumber.foreground': 'alphaStrong',
    // editorLink
    'editorLink.activeForeground': 'fgPrimary',
    // editorMarkerNavigation
    'editorMarkerNavigation.background': 'bgBase',
    // editorMarkerNavigationError
    'editorMarkerNavigationError.background': 'alphaFaint',
    'editorMarkerNavigationError.headerBackground': 'alphaFaint',
    // editorMarkerNavigationInfo
    'editorMarkerNavigationInfo.background': 'alphaFaint',
    'editorMarkerNavigationInfo.headerBackground': 'alphaFaint',
    // editorMarkerNavigationWarning
    'editorMarkerNavigationWarning.background': 'alphaFaint',
    'editorMarkerNavigationWarning.headerBackground': 'alphaFaint',
    // editorMinimap
    'editorMinimap.inlineChatInserted': 'fgTertiary',
    // editorMultiCursor
    'editorMultiCursor.primary.background': 'bgBase',
    'editorMultiCursor.primary.foreground': 'fgPrimary',
    'editorMultiCursor.secondary.background': 'bgBase',
    'editorMultiCursor.secondary.foreground': 'fgSecondary',
    // editorOverviewRuler
    'editorOverviewRuler.addedForeground': 'alphaStrong',
    'editorOverviewRuler.background': null,
    'editorOverviewRuler.border': 'borderSubtle',
    'editorOverviewRuler.bracketMatchForeground': 'alphaStrong',
    'editorOverviewRuler.commentDraftForeground': 'alphaStrong',
    'editorOverviewRuler.commentForeground': 'alphaStrong',
    'editorOverviewRuler.commentUnresolvedForeground': 'alphaStrong',
    'editorOverviewRuler.commonContentForeground': 'alphaStrong',
    'editorOverviewRuler.currentContentForeground': 'alphaStrong',
    'editorOverviewRuler.deletedForeground': 'alphaStrong',
    'editorOverviewRuler.errorForeground': 'fgMuted',
    'editorOverviewRuler.findMatchForeground': 'alphaStrong',
    'editorOverviewRuler.incomingContentForeground': 'alphaStrong',
    'editorOverviewRuler.infoForeground': 'alphaStrong',
    'editorOverviewRuler.inlineChatInserted': 'alphaStrong',
    'editorOverviewRuler.inlineChatRemoved': 'alphaStrong',
    'editorOverviewRuler.modifiedForeground': 'alphaStrong',
    'editorOverviewRuler.rangeHighlightForeground': 'alphaStrong',
    'editorOverviewRuler.selectionHighlightForeground': 'alphaStrong',
    'editorOverviewRuler.warningForeground': 'fgMuted',
    'editorOverviewRuler.wordHighlightForeground': 'alphaStrong',
    'editorOverviewRuler.wordHighlightStrongForeground': 'alphaStrong',
    'editorOverviewRuler.wordHighlightTextForeground': 'alphaStrong',
    // editorPane
    'editorPane.background': 'bgRaised',
    // editorRuler
    'editorRuler.foreground': 'borderSubtle',
    // editorStickyScroll
    'editorStickyScroll.background': 'bgRaised',
    'editorStickyScroll.border': 'borderSubtle',
    'editorStickyScroll.shadow': 'shadow',
    // editorStickyScrollGutter
    'editorStickyScrollGutter.background': 'bgWidget',
    // editorStickyScrollHover
    'editorStickyScrollHover.background': 'bgRaised',
    // editorSuggestWidget
    'editorSuggestWidget.background': 'bgWidget',
    'editorSuggestWidget.border': 'borderSubtle',
    'editorSuggestWidget.focusHighlightForeground': 'fgPrimary',
    'editorSuggestWidget.focusOutline': 'borderFocus',
    'editorSuggestWidget.foreground': 'fgSecondary',
    'editorSuggestWidget.highlightForeground': 'fgPrimary',
    'editorSuggestWidget.selectedBackground': 'selectionBg',
    'editorSuggestWidget.selectedForeground': 'fgPrimary',
    'editorSuggestWidget.selectedIconForeground': 'fgPrimary',
    // editorSuggestWidgetStatus
    'editorSuggestWidgetStatus.foreground': 'fgSecondary',
    // editorUnicodeHighlight
    'editorUnicodeHighlight.background': 'alphaFaint',
    'editorUnicodeHighlight.border': 'borderSubtle',
    // editorUnnecessaryCode
    'editorUnnecessaryCode.border': 'borderSubtle',
    'editorUnnecessaryCode.opacity': 'fgTertiary',
    // editorWarning
    'editorWarning.background': null,
    'editorWarning.border': null,
    'editorWarning.foreground': 'fgSecondary',
    // editorWhitespace
    'editorWhitespace.foreground': 'fgMuted',
    // editorWidget
    'editorWidget.background': 'bgWidget',
    'editorWidget.border': 'borderSubtle',
    'editorWidget.foreground': 'fgSecondary',
    'editorWidget.resizeBorder': 'borderFocus',
    // errorForeground
    'errorForeground': 'fgPrimary',
    // extensionBadge
    'extensionBadge.remoteBackground': 'invertBg',
    'extensionBadge.remoteForeground': 'invertFg',
    // extensionButton
    'extensionButton.background': 'bgBase',
    'extensionButton.border': 'borderSubtle',
    'extensionButton.foreground': 'fgSecondary',
    'extensionButton.hoverBackground': 'bgRaised',
    'extensionButton.prominentBackground': 'invertBgMuted',
    'extensionButton.prominentForeground': 'invertFg',
    'extensionButton.prominentHoverBackground': 'invertBg',
    'extensionButton.separator': 'borderSubtle',
    // extensionIcon
    'extensionIcon.preReleaseForeground': 'fgSecondary',
    'extensionIcon.privateForeground': 'fgSecondary',
    'extensionIcon.sponsorForeground': 'fgSecondary',
    'extensionIcon.starForeground': 'fgSecondary',
    'extensionIcon.verifiedForeground': 'fgSecondary',
    // focusBorder
    'focusBorder': 'borderFocus',
    // foreground
    'foreground': 'fgSecondary',
    // git
    'git.blame.editorDecorationForeground': 'fgSecondary',
    // gitDecoration
    'gitDecoration.addedResourceForeground': 'fgSecondary',
    'gitDecoration.conflictingResourceForeground': 'fgPrimary',
    'gitDecoration.deletedResourceForeground': 'fgTertiary',
    'gitDecoration.ignoredResourceForeground': 'fgMuted',
    'gitDecoration.modifiedResourceForeground': 'fgSecondary',
    'gitDecoration.renamedResourceForeground': 'fgSecondary',
    'gitDecoration.stageDeletedResourceForeground': 'fgTertiary',
    'gitDecoration.stageModifiedResourceForeground': 'fgSecondary',
    'gitDecoration.submoduleResourceForeground': 'fgTertiary',
    'gitDecoration.untrackedResourceForeground': 'fgTertiary',
    // icon
    'icon.foreground': 'fgSecondary',
    // inactiveSessionView
    'inactiveSessionView.background': 'bgBase',
    'inactiveSessionView.foreground': 'fgMuted',
    // inlineChat
    'inlineChat.background': 'bgWidget',
    'inlineChat.border': 'borderSubtle',
    'inlineChat.foreground': 'fgSecondary',
    'inlineChat.shadow': 'shadow',
    // inlineChatDiff
    'inlineChatDiff.inserted': 'alphaFaint',
    'inlineChatDiff.removed': 'alphaMid',
    // inlineChatInput
    'inlineChatInput.background': 'bgWidget',
    'inlineChatInput.border': 'borderSubtle',
    'inlineChatInput.focusBorder': 'borderFocus',
    'inlineChatInput.placeholderForeground': 'fgSecondary',
    // inlineEdit
    'inlineEdit.gutterIndicator.background': 'bgBase',
    'inlineEdit.gutterIndicator.primaryBackground': 'bgBase',
    'inlineEdit.gutterIndicator.primaryBorder': 'borderSubtle',
    'inlineEdit.gutterIndicator.primaryForeground': 'fgSecondary',
    'inlineEdit.gutterIndicator.secondaryBackground': 'bgRaised',
    'inlineEdit.gutterIndicator.secondaryBorder': 'borderSubtle',
    'inlineEdit.gutterIndicator.secondaryForeground': 'fgSecondary',
    'inlineEdit.gutterIndicator.successfulBackground': 'bgBase',
    'inlineEdit.gutterIndicator.successfulBorder': 'borderSubtle',
    'inlineEdit.gutterIndicator.successfulForeground': 'fgSecondary',
    'inlineEdit.modifiedBackground': 'alphaFaint',
    'inlineEdit.modifiedBorder': 'borderSubtle',
    'inlineEdit.modifiedChangedLineBackground': 'alphaFaint',
    'inlineEdit.modifiedChangedTextBackground': 'alphaFaint',
    'inlineEdit.originalBackground': 'alphaFaint', // must be translucent
    'inlineEdit.originalBorder': 'borderSubtle',
    'inlineEdit.originalChangedLineBackground': 'alphaFaint', // must be translucent
    'inlineEdit.originalChangedTextBackground': 'alphaMid', // must be translucent
    'inlineEdit.tabWillAcceptModifiedBorder': 'borderSubtle',
    'inlineEdit.tabWillAcceptOriginalBorder': 'borderSubtle',
    // input
    'input.background': 'bgSunken',
    'input.border': 'borderSubtle',
    'input.foreground': 'fgPrimary',
    'input.placeholderForeground': 'fgMuted',
    // inputOption
    'inputOption.activeBackground': 'selectionBg',
    'inputOption.activeBorder': 'borderFocus',
    'inputOption.activeForeground': 'fgPrimary',
    'inputOption.hoverBackground': 'bgRaised',
    // inputValidation
    'inputValidation.errorBackground': 'alphaFaint',
    'inputValidation.errorBorder': 'borderSubtle',
    'inputValidation.errorForeground': 'fgPrimary',
    'inputValidation.infoBackground': 'alphaFaint',
    'inputValidation.infoBorder': 'borderSubtle',
    'inputValidation.infoForeground': 'fgTertiary',
    'inputValidation.warningBackground': 'alphaFaint',
    'inputValidation.warningBorder': 'borderSubtle',
    'inputValidation.warningForeground': 'fgSecondary',
    // interactive
    'interactive.activeCodeBorder': 'borderSubtle',
    'interactive.inactiveCodeBorder': 'borderSubtle',
    // keybindingLabel
    'keybindingLabel.background': 'bgRaised',
    'keybindingLabel.border': 'borderSubtle',
    'keybindingLabel.bottomBorder': 'borderSubtle',
    'keybindingLabel.foreground': 'fgSecondary',
    // keybindingTable
    'keybindingTable.headerBackground': 'bgRaised',
    'keybindingTable.rowsBackground': 'bgBase',
    // list
    'list.activeSelectionBackground': 'selectionBgStrong',
    'list.activeSelectionForeground': 'fgPrimary',
    'list.activeSelectionIconForeground': 'fgPrimary',
    'list.deemphasizedForeground': 'fgMuted',
    'list.dropBackground': 'alphaMid',
    'list.dropBetweenBackground': 'fgSecondary',
    'list.errorForeground': 'fgPrimary',
    'list.filterMatchBackground': 'alphaMid',
    'list.filterMatchBorder': 'borderSubtle',
    'list.focusAndSelectionOutline': 'borderSubtle',
    'list.focusBackground': 'selectionBgStrong',
    'list.focusForeground': 'fgPrimary',
    'list.focusHighlightForeground': 'fgPrimary',
    'list.focusOutline': 'borderFocus',
    'list.highlightForeground': 'fgPrimary',
    'list.hoverBackground': 'alphaMid',
    'list.hoverForeground': 'fgPrimary',
    'list.inactiveFocusBackground': 'selectionBg',
    'list.inactiveFocusOutline': 'borderFocus',
    'list.inactiveSelectionBackground': 'selectionBg',
    'list.inactiveSelectionForeground': 'fgPrimary',
    'list.inactiveSelectionIconForeground': 'fgPrimary',
    'list.invalidItemForeground': 'fgMuted',
    'list.warningForeground': 'fgSecondary',
    // listFilterWidget
    'listFilterWidget.background': 'bgWidget',
    'listFilterWidget.noMatchesOutline': 'borderSubtle',
    'listFilterWidget.outline': 'borderSubtle',
    'listFilterWidget.shadow': 'shadow',
    // markdownAlert
    'markdownAlert.caution.foreground': 'fgSecondary',
    'markdownAlert.important.foreground': 'fgSecondary',
    'markdownAlert.note.foreground': 'fgSecondary',
    'markdownAlert.tip.foreground': 'fgSecondary',
    'markdownAlert.warning.foreground': 'fgSecondary',
    // mcpIcon
    'mcpIcon.starForeground': 'fgSecondary',
    // menu
    'menu.background': 'bgWidget',
    'menu.border': 'borderSubtle',
    'menu.foreground': 'fgSecondary',
    'menu.selectionBackground': 'selectionBg',
    'menu.selectionBorder': null,
    'menu.selectionForeground': 'fgPrimary',
    'menu.separatorBackground': 'borderSubtle',
    // menubar
    'menubar.selectionBackground': 'selectionBg',
    'menubar.selectionBorder': null,
    'menubar.selectionForeground': 'fgPrimary',
    // merge
    'merge.border': 'borderSubtle',
    'merge.commonContentBackground': 'alphaFaint',
    'merge.commonHeaderBackground': 'alphaMid',
    'merge.currentContentBackground': 'alphaMid',
    'merge.currentHeaderBackground': 'alphaStrong',
    'merge.incomingContentBackground': 'alphaStrong',
    'merge.incomingHeaderBackground': 'selectionBgStrong',
    // mergeEditor
    'mergeEditor.change.background': 'alphaMid',
    'mergeEditor.change.word.background': 'alphaStrong',
    'mergeEditor.changeBase.background': 'alphaFaint',
    'mergeEditor.changeBase.word.background': 'alphaMid',
    'mergeEditor.conflict.handled.minimapOverViewRuler': 'alphaMid',
    'mergeEditor.conflict.handledFocused.border': 'borderSubtle',
    'mergeEditor.conflict.handledUnfocused.border': 'alphaMid',
    'mergeEditor.conflict.input1.background': 'alphaMid',
    'mergeEditor.conflict.input2.background': 'alphaStrong',
    'mergeEditor.conflict.unhandled.minimapOverViewRuler': 'fgMuted',
    'mergeEditor.conflict.unhandledFocused.border': 'fgPrimary',
    'mergeEditor.conflict.unhandledUnfocused.border': 'fgMuted',
    'mergeEditor.conflictingLines.background': 'alphaMid',
    // minimap
    'minimap.background': 'bgBase',
    'minimap.chatEditHighlight': 'alphaMid',
    'minimap.errorHighlight': 'fgMuted',
    'minimap.findMatchHighlight': 'alphaStrong',
    'minimap.foregroundOpacity': null,
    'minimap.infoHighlight': 'alphaMid',
    'minimap.selectionHighlight': 'alphaStrong',
    'minimap.selectionOccurrenceHighlight': 'alphaMid',
    'minimap.warningHighlight': 'alphaStrong',
    // minimapGutter
    'minimapGutter.addedBackground': 'fgMuted',
    'minimapGutter.deletedBackground': 'fgPrimary',
    'minimapGutter.modifiedBackground': 'fgTertiary',
    // minimapSlider
    'minimapSlider.activeBackground': 'alphaMid',
    'minimapSlider.background': 'alphaFaint',
    'minimapSlider.hoverBackground': 'alphaMid',
    // multiDiffEditor
    'multiDiffEditor.background': 'alphaMid',
    'multiDiffEditor.border': 'borderSubtle',
    'multiDiffEditor.headerBackground': 'alphaStrong',
    // notebook
    'notebook.cellBorderColor': 'borderSubtle',
    'notebook.cellEditorBackground': 'bgBase',
    'notebook.cellHoverBackground': 'bgRaised',
    'notebook.cellInsertionIndicator': 'fgTertiary',
    'notebook.cellStatusBarItemHoverBackground': 'bgRaised',
    'notebook.cellToolbarSeparator': 'fgTertiary',
    'notebook.editorBackground': 'bgBase',
    'notebook.focusedCellBackground': 'selectionBg',
    'notebook.focusedCellBorder': 'borderSubtle',
    'notebook.focusedEditorBorder': 'borderSubtle',
    'notebook.inactiveFocusedCellBorder': 'borderSubtle',
    'notebook.inactiveSelectedCellBorder': 'borderSubtle',
    'notebook.outputContainerBackgroundColor': 'bgBase',
    'notebook.outputContainerBorderColor': 'borderSubtle',
    'notebook.selectedCellBackground': 'alphaMid',
    'notebook.selectedCellBorder': 'borderSubtle',
    'notebook.symbolHighlightBackground': 'alphaMid',
    // notebookEditorOverviewRuler
    'notebookEditorOverviewRuler.runningCellForeground': 'fgSecondary',
    // notebookScrollbarSlider
    'notebookScrollbarSlider.activeBackground': 'alphaStrong',
    'notebookScrollbarSlider.background': 'alphaMid',
    'notebookScrollbarSlider.hoverBackground': 'alphaStrong',
    // notebookStatusErrorIcon
    'notebookStatusErrorIcon.foreground': 'fgPrimary',
    // notebookStatusRunningIcon
    'notebookStatusRunningIcon.foreground': 'fgSecondary',
    // notebookStatusSuccessIcon
    'notebookStatusSuccessIcon.foreground': 'fgSecondary',
    // notificationCenter
    'notificationCenter.border': 'borderSubtle',
    // notificationCenterHeader
    'notificationCenterHeader.background': 'bgRaised',
    'notificationCenterHeader.foreground': 'fgPrimary',
    // notificationLink
    'notificationLink.foreground': 'fgPrimary',
    // notificationToast
    'notificationToast.border': 'borderSubtle',
    // notifications
    'notifications.background': 'bgWidget',
    'notifications.border': 'borderSubtle',
    'notifications.foreground': 'fgPrimary',
    // notificationsErrorIcon
    'notificationsErrorIcon.foreground': 'fgPrimary',
    // notificationsInfoIcon
    'notificationsInfoIcon.foreground': 'fgTertiary',
    // notificationsWarningIcon
    'notificationsWarningIcon.foreground': 'fgSecondary',
    // outputView
    'outputView.background': 'bgBase',
    // outputViewStickyScroll
    'outputViewStickyScroll.background': 'bgWidget',
    // panel
    'panel.background': 'bgSunken',
    'panel.border': 'borderSubtle',
    'panel.dropBorder': 'borderSubtle',
    // panelInput
    'panelInput.border': 'borderSubtle',
    // panelSection
    'panelSection.border': 'borderSubtle',
    'panelSection.dropBackground': 'alphaMid',
    // panelSectionHeader
    'panelSectionHeader.background': 'bgRaised',
    'panelSectionHeader.border': 'borderSubtle',
    'panelSectionHeader.foreground': 'fgPrimary',
    // panelStickyScroll
    'panelStickyScroll.background': 'bgWidget',
    'panelStickyScroll.border': 'borderSubtle',
    'panelStickyScroll.shadow': 'shadow',
    // panelTitle
    'panelTitle.activeBorder': 'fgPrimary',
    'panelTitle.activeForeground': 'fgPrimary',
    'panelTitle.border': 'borderSubtle',
    'panelTitle.inactiveForeground': 'fgMuted',
    // panelTitleBadge
    'panelTitleBadge.background': 'invertBg',
    'panelTitleBadge.foreground': 'invertFg',
    // peekView
    'peekView.border': 'borderFocus',
    // peekViewEditor
    'peekViewEditor.background': 'bgSunken',
    'peekViewEditor.matchHighlightBackground': 'alphaMid',
    'peekViewEditor.matchHighlightBorder': 'borderSubtle',
    // peekViewEditorGutter
    'peekViewEditorGutter.background': 'bgSunken',
    // peekViewEditorStickyScroll
    'peekViewEditorStickyScroll.background': 'bgWidget',
    // peekViewEditorStickyScrollGutter
    'peekViewEditorStickyScrollGutter.background': 'bgWidget',
    // peekViewResult
    'peekViewResult.background': 'bgRaised',
    'peekViewResult.fileForeground': 'fgPrimary',
    'peekViewResult.lineForeground': 'fgTertiary',
    'peekViewResult.matchHighlightBackground': 'alphaMid',
    'peekViewResult.selectionBackground': 'selectionBg',
    'peekViewResult.selectionForeground': 'fgPrimary',
    // peekViewTitle
    'peekViewTitle.background': 'bgRaised',
    // peekViewTitleDescription
    'peekViewTitleDescription.foreground': 'fgSecondary',
    // peekViewTitleLabel
    'peekViewTitleLabel.foreground': 'fgPrimary',
    // pickerGroup
    'pickerGroup.border': 'borderSubtle',
    'pickerGroup.foreground': 'fgPrimary',
    // ports
    'ports.iconRunningProcessForeground': 'fgSecondary',
    // problemsErrorIcon
    'problemsErrorIcon.foreground': 'fgPrimary',
    // problemsInfoIcon
    'problemsInfoIcon.foreground': 'fgTertiary',
    // problemsWarningIcon
    'problemsWarningIcon.foreground': 'fgSecondary',
    // profileBadge
    'profileBadge.background': 'invertBg',
    'profileBadge.foreground': 'invertFg',
    // profiles
    'profiles.sashBorder': 'borderSubtle',
    // progressBar
    'progressBar.background': 'fgPrimary',
    // quickInput
    'quickInput.background': 'bgWidget',
    'quickInput.foreground': 'fgSecondary',
    'quickInput.list.focusBackground': null, // deprecated -> quickInputList.focusBackground
    // quickInputList
    'quickInputList.focusBackground': 'selectionBg',
    'quickInputList.focusForeground': 'fgPrimary',
    'quickInputList.focusHighlightForeground': 'fgPrimary',
    'quickInputList.focusIconForeground': 'fgPrimary',
    // quickInputTitle
    'quickInputTitle.background': 'bgRaised',
    // radio
    'radio.activeBackground': 'selectionBg',
    'radio.activeBorder': 'borderFocus',
    'radio.activeForeground': 'fgPrimary',
    'radio.inactiveBackground': 'bgBase',
    'radio.inactiveBorder': 'borderFocus',
    'radio.inactiveForeground': 'fgMuted',
    'radio.inactiveHoverBackground': 'bgRaised',
    // sash
    'sash.hoverBorder': 'borderFocus',
    // scmGraph
    'scmGraph.foreground1': 'graphLane1',
    'scmGraph.foreground2': 'graphLane2',
    'scmGraph.foreground3': 'graphLane3',
    'scmGraph.foreground4': 'graphLane4',
    'scmGraph.foreground5': 'graphLane5',
    // The three ref colors are badge *backgrounds*, and they all share one text
    // color (historyItemHoverLabelForeground), so they must stay on the ink side
    // of the ladder. Only two rungs read as a badge: bg-on-fgl is 1.5-3:1.
    'scmGraph.historyItemBaseRefColor': 'fgSecondary',
    'scmGraph.historyItemHoverAdditionsForeground': 'fgSecondary',
    'scmGraph.historyItemHoverDefaultLabelBackground': 'alphaStrong',
    'scmGraph.historyItemHoverDefaultLabelForeground': 'fgSecondary',
    'scmGraph.historyItemHoverDeletionsForeground': 'fgSecondary',
    'scmGraph.historyItemHoverLabelForeground': 'invertFg',
    'scmGraph.historyItemRefColor': 'invertBg',
    'scmGraph.historyItemRemoteRefColor': 'fgSecondary',
    // scrollbar
    'scrollbar.background': 'bgBase',
    'scrollbar.shadow': 'shadow',
    // scrollbarSlider
    'scrollbarSlider.activeBackground': 'alphaStrong',
    'scrollbarSlider.background': 'alphaMid',
    'scrollbarSlider.hoverBackground': 'alphaStrong',
    // search
    'search.resultsInfoForeground': 'fgTertiary',
    // searchEditor
    'searchEditor.findMatchBackground': 'alphaMid',
    'searchEditor.findMatchBorder': 'borderSubtle',
    'searchEditor.textInputBorder': 'borderSubtle',
    // selection
    // text fields can't recolor selected text, so solid fg would hide it —
    // translucent fg is the only readable option here
    'selection.background': 'alphaStrong',
    // settings
    'settings.checkboxBackground': 'bgBase',
    'settings.checkboxBorder': 'borderSubtle',
    'settings.checkboxForeground': 'fgSecondary',
    'settings.dropdownBackground': 'bgWidget',
    'settings.dropdownBorder': 'borderSubtle',
    'settings.dropdownForeground': 'fgSecondary',
    'settings.dropdownListBorder': 'borderSubtle',
    'settings.focusedRowBackground': 'bgRaised',
    'settings.focusedRowBorder': 'borderFocus',
    'settings.headerBorder': 'borderSubtle',
    'settings.headerForeground': 'fgPrimary',
    'settings.modifiedItemIndicator': 'fgSecondary',
    'settings.numberInputBackground': 'bgBase',
    'settings.numberInputBorder': 'borderSubtle',
    'settings.numberInputForeground': 'fgSecondary',
    'settings.rowHoverBackground': 'bgRaised',
    'settings.sashBorder': 'borderSubtle',
    'settings.settingsHeaderHoverForeground': 'fgPrimary',
    'settings.textInputBackground': 'bgBase',
    'settings.textInputBorder': 'borderSubtle',
    'settings.textInputForeground': 'fgSecondary',
    // sideBar
    'sideBar.background': 'bgBase',
    'sideBar.border': 'borderSubtle',
    'sideBar.dropBackground': 'alphaMid',
    'sideBar.foreground': 'fgSecondary',
    // sideBarActivityBarTop
    'sideBarActivityBarTop.border': 'borderSubtle',
    // sideBarSectionHeader
    'sideBarSectionHeader.background': 'bgRaised',
    'sideBarSectionHeader.border': 'borderSubtle',
    'sideBarSectionHeader.foreground': 'fgPrimary',
    // sideBarStickyScroll
    'sideBarStickyScroll.background': 'bgWidget',
    'sideBarStickyScroll.border': 'borderSubtle',
    'sideBarStickyScroll.shadow': 'shadow',
    // sideBarTitle
    'sideBarTitle.background': 'bgBase',
    'sideBarTitle.border': 'borderSubtle',
    'sideBarTitle.foreground': 'fgPrimary',
    // sideBySideEditor
    'sideBySideEditor.horizontalBorder': 'borderSubtle',
    'sideBySideEditor.verticalBorder': 'borderSubtle',
    // simpleFindWidget
    'simpleFindWidget.sashBorder': 'borderSubtle',
    // statusBar
    'statusBar.background': 'invertBgMuted',
    'statusBar.border': 'borderSubtle',
    // debugging flips the status bar back to normal video so it reads as a
    // distinct mode against the reverse-video default
    'statusBar.debuggingBackground': 'bgBase',
    'statusBar.debuggingBorder': 'borderSubtle',
    'statusBar.debuggingForeground': 'fgPrimary',
    'statusBar.focusBorder': 'invertFg',
    'statusBar.foreground': 'invertFg',
    'statusBar.noFolderBackground': 'invertBgMuted',
    'statusBar.noFolderBorder': 'borderSubtle',
    'statusBar.noFolderForeground': 'invertFg',
    // statusBarItem
    // generic items sit on the reverse-video bar and flip to normal video on
    // hover; the alert items (error/warning/remote/prominent) sit in normal
    // video at rest so they punch through the reverse-video bar, then brighten
    // to the selection block on hover
    'statusBarItem.activeBackground': 'bgBase',
    'statusBarItem.compactHoverBackground': 'bgRaised',
    'statusBarItem.errorBackground': 'bgBase',
    'statusBarItem.errorForeground': 'fgPrimary',
    'statusBarItem.errorHoverBackground': 'bgRaised',
    'statusBarItem.errorHoverForeground': 'fgPrimary',
    'statusBarItem.focusBorder': 'borderFocus',
    'statusBarItem.hoverBackground': 'bgBase',
    'statusBarItem.hoverForeground': 'fgPrimary',
    'statusBarItem.offlineBackground': 'bgBase',
    'statusBarItem.offlineForeground': 'fgMuted',
    'statusBarItem.offlineHoverBackground': 'bgRaised',
    'statusBarItem.offlineHoverForeground': 'fgSecondary',
    'statusBarItem.prominentBackground': 'bgBase',
    'statusBarItem.prominentForeground': 'fgPrimary',
    'statusBarItem.prominentHoverBackground': 'bgRaised',
    'statusBarItem.prominentHoverForeground': 'fgPrimary',
    'statusBarItem.remoteBackground': 'bgBase',
    'statusBarItem.remoteForeground': 'fgPrimary',
    'statusBarItem.remoteHoverBackground': 'bgRaised',
    'statusBarItem.remoteHoverForeground': 'fgPrimary',
    'statusBarItem.warningBackground': 'bgBase',
    'statusBarItem.warningForeground': 'fgPrimary',
    'statusBarItem.warningHoverBackground': 'bgRaised',
    'statusBarItem.warningHoverForeground': 'fgPrimary',
    // strongForeground
    'strongForeground': 'fgPrimary',
    // surface
    'surface.background': 'bgBase',
    'surface.border': 'borderSubtle',
    'surface.foreground': 'fgSecondary',
    // symbolIcon
    'symbolIcon.arrayForeground': 'fgSecondary',
    'symbolIcon.booleanForeground': 'fgSecondary',
    'symbolIcon.classForeground': 'fgSecondary',
    'symbolIcon.colorForeground': 'fgSecondary',
    'symbolIcon.constantForeground': 'fgSecondary',
    'symbolIcon.constructorForeground': 'fgSecondary',
    'symbolIcon.enumeratorForeground': 'fgSecondary',
    'symbolIcon.enumeratorMemberForeground': 'fgSecondary',
    'symbolIcon.eventForeground': 'fgSecondary',
    'symbolIcon.fieldForeground': 'fgSecondary',
    'symbolIcon.fileForeground': 'fgSecondary',
    'symbolIcon.folderForeground': 'fgSecondary',
    'symbolIcon.functionForeground': 'fgSecondary',
    'symbolIcon.interfaceForeground': 'fgSecondary',
    'symbolIcon.keyForeground': 'fgSecondary',
    'symbolIcon.keywordForeground': 'fgSecondary',
    'symbolIcon.methodForeground': 'fgSecondary',
    'symbolIcon.moduleForeground': 'fgSecondary',
    'symbolIcon.namespaceForeground': 'fgSecondary',
    'symbolIcon.nullForeground': 'fgSecondary',
    'symbolIcon.numberForeground': 'fgSecondary',
    'symbolIcon.objectForeground': 'fgSecondary',
    'symbolIcon.operatorForeground': 'fgSecondary',
    'symbolIcon.packageForeground': 'fgSecondary',
    'symbolIcon.propertyForeground': 'fgSecondary',
    'symbolIcon.referenceForeground': 'fgSecondary',
    'symbolIcon.snippetForeground': 'fgSecondary',
    'symbolIcon.stringForeground': 'fgSecondary',
    'symbolIcon.structForeground': 'fgSecondary',
    'symbolIcon.textForeground': 'fgSecondary',
    'symbolIcon.typeParameterForeground': 'fgSecondary',
    'symbolIcon.unitForeground': 'fgSecondary',
    'symbolIcon.variableForeground': 'fgSecondary',
    // tab
    'tab.activeBackground': 'selectionBg',
    'tab.activeBorder': null,
    'tab.activeBorderTop': 'fgPrimary',
    'tab.activeForeground': 'fgPrimary',
    'tab.activeModifiedBorder': 'borderSubtle',
    'tab.border': 'borderSubtle',
    'tab.dragAndDropBorder': 'borderSubtle',
    'tab.hoverBackground': 'bgRaised',
    'tab.hoverBorder': 'borderSubtle',
    'tab.hoverForeground': 'fgSecondary',
    'tab.inactiveBackground': 'bgSunken',
    'tab.inactiveForeground': 'fgMuted',
    'tab.inactiveModifiedBorder': 'borderSubtle',
    'tab.lastPinnedBorder': 'borderSubtle',
    'tab.selectedBackground': 'selectionBg',
    'tab.selectedBorderTop': 'borderFocus',
    'tab.selectedForeground': 'fgPrimary',
    'tab.unfocusedActiveBackground': 'alphaMid',
    'tab.unfocusedActiveBorder': 'borderFocus',
    'tab.unfocusedActiveBorderTop': 'fgMuted',
    'tab.unfocusedActiveForeground': 'fgMuted',
    'tab.unfocusedActiveModifiedBorder': 'borderSubtle',
    'tab.unfocusedHoverBackground': 'alphaFaint',
    'tab.unfocusedHoverBorder': 'borderSubtle',
    'tab.unfocusedHoverForeground': 'fgMuted',
    'tab.unfocusedInactiveBackground': 'bgBase',
    'tab.unfocusedInactiveForeground': 'fgMuted',
    'tab.unfocusedInactiveModifiedBorder': 'borderSubtle',
    // terminal
    // The ANSI ramp — see the ansi* tokens. One role per slot: intensity is
    // standing in for hue here, so these are the one group where a 1:1 mapping
    // is the whole point.
    'terminal.ansiBlack': 'ansiBlack',
    'terminal.ansiBlue': 'ansiBlue',
    'terminal.ansiBrightBlack': 'ansiBrightBlack',
    'terminal.ansiBrightBlue': 'ansiBrightBlue',
    'terminal.ansiBrightCyan': 'ansiBrightCyan',
    'terminal.ansiBrightGreen': 'ansiBrightGreen',
    'terminal.ansiBrightMagenta': 'ansiBrightMagenta',
    'terminal.ansiBrightRed': 'ansiBrightRed',
    'terminal.ansiBrightWhite': 'ansiBrightWhite',
    'terminal.ansiBrightYellow': 'ansiBrightYellow',
    'terminal.ansiCyan': 'ansiCyan',
    'terminal.ansiGreen': 'ansiGreen',
    'terminal.ansiMagenta': 'ansiMagenta',
    'terminal.ansiRed': 'ansiRed',
    'terminal.ansiWhite': 'ansiWhite',
    'terminal.ansiYellow': 'ansiYellow',
    'terminal.background': 'bgSunken',
    'terminal.border': 'borderSubtle',
    'terminal.dropBackground': 'alphaMid',
    'terminal.findMatchBackground': 'alphaStrong',
    'terminal.findMatchBorder': 'borderSubtle',
    'terminal.findMatchHighlightBackground': 'alphaMid',
    'terminal.findMatchHighlightBorder': 'borderSubtle',
    'terminal.foreground': 'fgPrimary',
    'terminal.hoverHighlightBackground': 'alphaMid',
    'terminal.inactiveSelectionBackground': 'alphaMid',
    'terminal.initialHintForeground': 'fgTertiary',
    'terminal.selectionBackground': 'selectionBg',
    'terminal.selectionForeground': 'fgPrimary',
    'terminal.tab.activeBorder': 'borderFocus',
    // terminalCommandDecoration
    'terminalCommandDecoration.defaultBackground': 'alphaStrong',
    'terminalCommandDecoration.errorBackground': 'fgPrimary',
    'terminalCommandDecoration.successBackground': 'fgMuted',
    // terminalCommandGuide
    'terminalCommandGuide.foreground': 'fgSecondary',
    // terminalCursor
    'terminalCursor.background': 'bgSunken',
    'terminalCursor.foreground': 'fgPrimary',
    // terminalOverviewRuler
    'terminalOverviewRuler.border': 'borderSubtle',
    'terminalOverviewRuler.cursorForeground': 'fgSecondary',
    'terminalOverviewRuler.findMatchForeground': 'alphaStrong',
    // terminalStickyScroll
    'terminalStickyScroll.background': 'bgWidget',
    'terminalStickyScroll.border': 'borderSubtle',
    // terminalStickyScrollHover
    'terminalStickyScrollHover.background': 'bgRaised',
    // terminalSymbolIcon
    'terminalSymbolIcon.aliasForeground': 'fgSecondary',
    'terminalSymbolIcon.argumentForeground': 'fgSecondary',
    'terminalSymbolIcon.branchForeground': 'fgSecondary',
    'terminalSymbolIcon.commitForeground': 'fgSecondary',
    'terminalSymbolIcon.fileForeground': 'fgSecondary',
    'terminalSymbolIcon.flagForeground': 'fgSecondary',
    'terminalSymbolIcon.folderForeground': 'fgSecondary',
    'terminalSymbolIcon.inlineSuggestionForeground': 'fgSecondary',
    'terminalSymbolIcon.methodForeground': 'fgSecondary',
    'terminalSymbolIcon.optionForeground': 'fgSecondary',
    'terminalSymbolIcon.optionValueForeground': 'fgSecondary',
    'terminalSymbolIcon.pullRequestDoneForeground': 'fgSecondary',
    'terminalSymbolIcon.pullRequestForeground': 'fgSecondary',
    'terminalSymbolIcon.remoteForeground': 'fgSecondary',
    'terminalSymbolIcon.stashForeground': 'fgSecondary',
    'terminalSymbolIcon.symbolText': 'fgSecondary',
    'terminalSymbolIcon.symbolicLinkFileForeground': 'fgSecondary',
    'terminalSymbolIcon.symbolicLinkFolderForeground': 'fgSecondary',
    'terminalSymbolIcon.tagForeground': 'fgSecondary',
    // testing
    'testing.coverCountBadgeBackground': 'invertBg',
    'testing.coverCountBadgeForeground': 'invertFg',
    'testing.coveredBackground': 'alphaFaint',
    'testing.coveredBorder': 'borderSubtle',
    'testing.coveredGutterBackground': 'alphaMid',
    'testing.coveredMinimapBackground': 'alphaMid',
    'testing.iconErrored': 'fgPrimary',
    'testing.iconErrored.retired': 'fgSecondary',
    'testing.iconFailed': 'fgPrimary',
    'testing.iconFailed.retired': 'fgSecondary',
    'testing.iconPassed': 'fgSecondary',
    'testing.iconPassed.retired': 'fgMuted',
    'testing.iconQueued': 'fgMuted',
    'testing.iconQueued.retired': 'alphaStrong',
    'testing.iconSkipped': 'fgMuted',
    'testing.iconSkipped.retired': 'alphaStrong',
    'testing.iconUnset': 'fgMuted',
    'testing.iconUnset.retired': 'alphaStrong',
    'testing.message.error.badgeBackground': 'invertBg',
    'testing.message.error.badgeBorder': 'borderSubtle',
    'testing.message.error.badgeForeground': 'invertFg',
    'testing.message.error.lineBackground': 'alphaFaint',
    'testing.message.info.decorationForeground': 'fgTertiary',
    'testing.message.info.lineBackground': 'alphaFaint',
    'testing.messagePeekBorder': 'borderSubtle',
    'testing.messagePeekHeaderBackground': 'bgRaised',
    'testing.peekBorder': 'borderSubtle',
    'testing.peekHeaderBackground': 'bgRaised',
    'testing.runAction': 'fgTertiary',
    'testing.uncoveredBackground': 'alphaMid',
    'testing.uncoveredBorder': 'borderSubtle',
    'testing.uncoveredBranchBackground': 'alphaMid',
    'testing.uncoveredGutterBackground': 'alphaStrong',
    'testing.uncoveredMinimapBackground': 'alphaStrong',
    // textBlockQuote
    'textBlockQuote.background': 'bgRaised',
    'textBlockQuote.border': 'borderSubtle',
    // textCodeBlock
    'textCodeBlock.background': 'bgRaised',
    // textLink
    'textLink.activeForeground': 'fgPrimary',
    'textLink.foreground': 'fgPrimary',
    // textPreformat
    'textPreformat.background': 'bgRaised',
    'textPreformat.border': 'borderSubtle',
    'textPreformat.foreground': 'fgSecondary',
    // textSeparator
    'textSeparator.foreground': 'borderSubtle',
    // titleBar
    'titleBar.activeBackground': 'bgSunken',
    'titleBar.activeForeground': 'fgPrimary',
    'titleBar.border': 'borderSubtle',
    'titleBar.inactiveBackground': 'bgSunken',
    'titleBar.inactiveForeground': 'fgMuted',
    // toolbar
    // toolbar icons keep their own color, but they stay visible on the
    // muted highlight block
    'toolbar.activeBackground': 'selectionBg',
    'toolbar.hoverBackground': 'selectionBg',
    'toolbar.hoverOutline': null,
    // tree
    'tree.inactiveIndentGuidesStroke': 'alphaMid',
    'tree.indentGuidesStroke': 'alphaStrong',
    'tree.tableColumnsBorder': 'borderSubtle',
    'tree.tableOddRowsBackground': 'bgBase',
    // walkThrough
    'walkThrough.embeddedEditorBackground': 'bgSunken',
    // walkthrough
    'walkthrough.stepTitle.foreground': 'fgPrimary',
    // welcomePage
    'welcomePage.background': 'bgBase',
    // VS Code has these two descriptions swapped in its own schema: background
    // is the track, foreground is the bar. Roles here follow the behaviour.
    'welcomePage.progress.background': 'bgRaised',
    'welcomePage.progress.foreground': 'fgPrimary',
    'welcomePage.tileBackground': 'bgRaised',
    'welcomePage.tileBorder': 'borderSubtle',
    'welcomePage.tileHoverBackground': 'bgWidget',
    // widget
    'widget.border': 'borderSubtle',
    'widget.shadow': 'shadow',
    // window
    'window.activeBorder': 'borderFocus',
    'window.inactiveBorder': 'borderFocus',
};
