/**
 * Compute the opaque color from a foreground color with alpha channel against at solid color background.
 *
 * We need the ability to compute the same opaque foreground color as the transparent
 * version with a formula.
 *
 * https://graphicdesign.stackexchange.com/questions/113007/how-to-determine-the-equivalent-opaque-rgb-color-for-a-given-partially-transpare
 * https://stackoverflow.com/questions/15898740/how-to-convert-rgba-to-a-transparency-adjusted-hex
 *
 * @param {number[]} rgba
 * @param {number[]} brgb
 * @returns {number[]} the solid color
 */

const opaque = (rgba, brgb) => {
  // Color = Color * alpha + Background * (1 - alpha);
  let ret = new Array(4);
  let alpha = rgba[3];
  ret[3] = 1;

  for (i = 0; i < 3; i++) {
    ret[i] = Math.round(rgba[i] * alpha + brgb[i] * (1 - alpha));
  }

  return ret;
};

/**
 * Compute the opaque color from a foreground with alpha and solid background.
 *
 * @param {string} rgba (#rgba or #rrggbbaa)
 * @param {string} brgb (#rgb or #rrggbb)
 *
 * @returns {string} the solid color
 */

const opaqueRgb = (rgba, brgb) => {
  return rgbaArrayToStr(opaque(rgbaStrToArray(rgba), rgbaStrToArray(brgb)));
};

/**
 * Split a hex rgba-value (#rrggbbaa or #rgba).
 *
 * @param {string} rgba
 * @returns {number[]} rgba array
 */
const rgbaStrToArray = (rgba) => {
  let ret = new Array(4);

  const p1 = () => {
    ret[0] = parseInt(rgba[1] + rgba[1], 16);
    ret[1] = parseInt(rgba[2] + rgba[2], 16);
    ret[2] = parseInt(rgba[3] + rgba[3], 16);
  };

  const p2 = () => {
    ret[0] = parseInt(rgba[1] + rgba[2], 16);
    ret[1] = parseInt(rgba[3] + rgba[4], 16);
    ret[2] = parseInt(rgba[5] + rgba[6], 16);
  };

  if (rgba.length === 4) {
    // #rgb
    p1();
    ret[3] = 1;
  } else if (rgba.length === 5) {
    // #rgba
    p1();
    ret[3] = parseInt(rgba[4] + rgba[4], 16) / 0xff;
  } else if (rgba.length === 7) {
    // #rrggbb
    p2();
    ret[3] = 1;
  } else if (rgba.length === 9) {
    // #rrggbbaa
    p2();
    ret[3] = parseInt(rgba[7] + rgba[8], 16) / 0xff;
  }

  return ret;
};

/**
 * Join rgba-array.
 *
 * @param {number[]} rgba
 * @returns {string} rgba string
 */
const rgbaArrayToStr = (rgba) => {
  return (
    "#" +
    rgba
      .map(function (x, i) {
        let y = "0";
        if (i < 3) {
          y += x.toString(16);
        } else {
          y += Math.round(x * 0xff).toString(16);
        }
        return y.slice(-2);
      })
      .join("")
  );
};

/**
 * Create a CRT Theme programmatically. Serialize into json for inclusion
 * in theme extension.
 *
 * @param {string} name the name of the template
 * @param {string} type of template (dark, light, hc)
 * @param {string} fg foreground color (#rrggbb)
 * @param {string} bg background color (#rrggbb)
 * @param {string[]} opacities array of up to 16 opacities as hex strings "00" to "ff" to override defaults
 * @param {object} template template object with all possible color attributes
 *
 * @returns {any} the resulting template
 */

const crtTemplate = (name, type, fg, bg, opacities, template) => {
  // Default levels of opacity
  const ol = [];
  for (let i = 0; i < 16; i++) {
    let y = "0";
    y += Math.round(0xff - (i * 0xff) / 15).toString(16);
    ol[i] = y.slice(-2);
  }

  // Override levels of opacity
  if (opacities) {
    for (let i = 0; i < opacities.length; i++) {
      ol[i] = opacities[i];
    }
  }

  const fgc = {};

  for (let i = 0; i < ol.length; i++) {
    fgc["t" + i] = fg + ol[i];
    fgc["s" + i] = opaqueRgb(fgc["t" + i], bg);
  }

  let fg_ta = fgc.t7, //fg_sa = fgc.s7,
    fg_tb = fgc.t12,
    fg_sb = fgc.s12,
    fg_tc = fgc.t14; // fg_sc = fgc.s14;

  return {
    "$schema": "vscode://schemas/color-theme",
    name: name,
    type: type,
    colors: {
      "actionBar.toggledBackground": fg_ta,
      "activityBar.activeBackground": fg_tb,
      "activityBar.activeBorder": fg_ta,
      "activityBar.activeFocusBorder": fg_ta,
      "activityBar.background": bg,
      "activityBar.border": fg_ta,
      "activityBar.dropBorder": fg_ta,
      "activityBar.foreground": fg,
      "activityBar.inactiveForeground": fg_ta,
      "activityBarBadge.background": fg,
      "activityBarBadge.foreground": bg,
      "activityBarTop.activeBackground": fg_tb,
      "activityBarTop.activeBorder": fg_ta,
      "activityBarTop.background": bg,
      "activityBarTop.dropBorder": fg_ta,
      "activityBarTop.foreground": fg,
      "activityBarTop.inactiveForeground": fg_ta,
      "activityErrorBadge.background": fg,
      "activityErrorBadge.foreground": bg,
      "activityWarningBadge.background": fg,
      "activityWarningBadge.foreground": bg,
      "badge.background": bg,
      "badge.foreground": fg,
      "banner.background": bg,
      "banner.foreground": fg,
      "banner.iconForeground": fg,
      "breadcrumb.activeSelectionForeground": fg,
      "breadcrumb.background": bg,
      "breadcrumb.focusForeground": fg,
      "breadcrumb.foreground": fg_ta,
      "breadcrumbPicker.background": bg,
      "button.background": bg,
      "button.border": "default",
      "button.foreground": fg,
      "button.hoverBackground": fg_ta,
      "button.secondaryBackground": bg,
      "button.secondaryForeground": fg,
      "button.secondaryHoverBackground": bg,
      "button.separator": "default",
      "chart.axis": "default",
      "chart.guide": "default",
      "chart.line": "default",
      "charts.blue": "default",
      "charts.foreground": fg,
      "charts.green": "default",
      "charts.lines": "default",
      "charts.orange": "default",
      "charts.purple": "default",
      "charts.red": "default",
      "charts.yellow": "default",
      "chat.avatarBackground": bg,
      "chat.avatarForeground": fg,
      "chat.editedFileForeground": fg,
      "chat.requestBackground": bg,
      "chat.requestBorder": "default",
      "chat.slashCommandBackground": bg,
      "chat.slashCommandForeground": fg,
      "checkbox.background": bg,
      "checkbox.border": fg_ta,
      "checkbox.foreground": fg,
      "checkbox.selectBackground": bg,
      "checkbox.selectBorder": "default",
      "commandCenter.activeBackground": bg,
      "commandCenter.activeBorder": "default",
      "commandCenter.activeForeground": fg,
      "commandCenter.background": bg,
      "commandCenter.border": "default",
      "commandCenter.debuggingBackground": bg,
      "commandCenter.foreground": fg,
      "commandCenter.inactiveBorder": "default",
      "commandCenter.inactiveForeground": fg,
      "commentsView.resolvedIcon": "default",
      "commentsView.unresolvedIcon": "default",
      "contrastActiveBorder": "default",
      "contrastBorder": "default",
      "debugConsole.errorForeground": fg,
      "debugConsole.infoForeground": fg,
      "debugConsole.sourceForeground": fg,
      "debugConsole.warningForeground": fg,
      "debugConsoleInputIcon.foreground": fg,
      "debugExceptionWidget.background": bg,
      "debugExceptionWidget.border": fg_ta,
      "debugIcon.breakpointCurrentStackframeForeground": fg,
      "debugIcon.breakpointDisabledForeground": fg_tb,
      "debugIcon.breakpointForeground": fg,
      "debugIcon.breakpointStackframeForeground": fg,
      "debugIcon.breakpointUnverifiedForeground": fg,
      "debugIcon.continueForeground": fg,
      "debugIcon.disconnectForeground": fg,
      "debugIcon.pauseForeground": fg,
      "debugIcon.restartForeground": fg,
      "debugIcon.startForeground": fg,
      "debugIcon.stepBackForeground": fg,
      "debugIcon.stepIntoForeground": fg,
      "debugIcon.stepOutForeground": fg,
      "debugIcon.stepOverForeground": fg,
      "debugIcon.stopForeground": fg,
      "debugTokenExpression.boolean": fg,
      "debugTokenExpression.error": fg,
      "debugTokenExpression.name": fg,
      "debugTokenExpression.number": fg,
      "debugTokenExpression.string": fg,
      "debugTokenExpression.type": "default",
      "debugTokenExpression.value": fg,
      "debugToolBar.background": bg,
      "debugToolBar.border": fg_ta,
      "debugView.exceptionLabelBackground": bg,
      "debugView.exceptionLabelForeground": fg,
      "debugView.stateLabelBackground": bg,
      "debugView.stateLabelForeground": fg,
      "debugView.valueChangedHighlight": fg_ta,
      "descriptionForeground": fg,
      "diffEditor.border": fg_ta,
      "diffEditor.diagonalFill": fg_tc,
      "diffEditor.insertedLineBackground": bg,
      "diffEditor.insertedTextBackground": fg_tb,
      "diffEditor.insertedTextBorder": "default",
      "diffEditor.move.border": "default",
      "diffEditor.moveActive.border": "default",
      "diffEditor.removedLineBackground": bg,
      "diffEditor.removedTextBackground": fg_tb,
      "diffEditor.removedTextBorder": "default",
      "diffEditor.unchangedCodeBackground": bg,
      "diffEditor.unchangedRegionBackground": bg,
      "diffEditor.unchangedRegionForeground": fg,
      "diffEditor.unchangedRegionShadow": "default",
      "diffEditorGutter.insertedLineBackground": bg,
      "diffEditorGutter.removedLineBackground": bg,
      "diffEditorOverview.insertedForeground": fg,
      "diffEditorOverview.removedForeground": fg,
      "disabledForeground": fg,
      "dropdown.background": bg,
      "dropdown.border": fg_ta,
      "dropdown.foreground": fg,
      "dropdown.listBackground": bg,
      "editor.background": bg,
      "editor.compositionBorder": "default",
      "editor.findMatchBackground": fg_ta,
      "editor.findMatchBorder": fg_ta,
      "editor.findMatchForeground": fg,
      "editor.findMatchHighlightBackground": fg_tb,
      "editor.findMatchHighlightBorder": fg_ta,
      "editor.findMatchHighlightForeground": fg,
      "editor.findRangeHighlightBackground": fg_tb,
      "editor.findRangeHighlightBorder": fg_ta,
      "editor.focusedStackFrameHighlightBackground": bg,
      "editor.foldBackground": fg_tb,
      "editor.foldPlaceholderForeground": fg,
      "editor.foreground": fg,
      "editor.hoverHighlightBackground": fg_tb,
      "editor.inactiveSelectionBackground": fg_tb,
      "editorIndentGuide.activeBackground": "default",
      "editorIndentGuide.background": "default",
      "editor.inlineValuesBackground": bg,
      "editor.inlineValuesForeground": fg,
      "editor.lineHighlightBackground": fg_tc,
      "editor.lineHighlightBorder": "default",
      "editor.linkedEditingBackground": bg,
      "editor.placeholder.foreground": fg,
      "editor.rangeHighlightBackground": fg_tb,
      "editor.rangeHighlightBorder": fg_ta,
      "editor.selectionBackground": fg_tb,
      "editor.selectionForeground": fg,
      "editor.selectionHighlightBackground": fg_tb,
      "editor.selectionHighlightBorder": fg_ta,
      "editor.snippetFinalTabstopHighlightBackground": bg,
      "editor.snippetFinalTabstopHighlightBorder": fg_ta,
      "editor.snippetTabstopHighlightBackground": bg,
      "editor.snippetTabstopHighlightBorder": fg_ta,
      "editor.stackFrameHighlightBackground": bg,
      "editor.symbolHighlightBackground": fg_tb,
      "editor.symbolHighlightBorder": fg_ta,
      "editor.wordHighlightBackground": fg_tb,
      "editor.wordHighlightBorder": fg_ta,
      "editor.wordHighlightStrongBackground": fg_ta,
      "editor.wordHighlightStrongBorder": fg_ta,
      "editor.wordHighlightTextBackground": bg,
      "editor.wordHighlightTextBorder": "default",
      "editorActionList.background": bg,
      "editorActionList.focusBackground": bg,
      "editorActionList.focusForeground": fg,
      "editorActionList.foreground": fg,
      "editorActiveLineNumber.foreground": fg,
      "editorBracketHighlight.foreground1": "default",
      "editorBracketHighlight.foreground2": "default",
      "editorBracketHighlight.foreground3": "default",
      "editorBracketHighlight.foreground4": "default",
      "editorBracketHighlight.foreground5": "default",
      "editorBracketHighlight.foreground6": "default",
      "editorBracketHighlight.unexpectedBracket.foreground": fg,
      "editorBracketMatch.background": bg,
      "editorBracketMatch.border": fg_ta,
      "editorBracketPairGuide.activeBackground1": "default",
      "editorBracketPairGuide.activeBackground2": "default",
      "editorBracketPairGuide.activeBackground3": "default",
      "editorBracketPairGuide.activeBackground4": "default",
      "editorBracketPairGuide.activeBackground5": "default",
      "editorBracketPairGuide.activeBackground6": "default",
      "editorBracketPairGuide.background1": "default",
      "editorBracketPairGuide.background2": "default",
      "editorBracketPairGuide.background3": "default",
      "editorBracketPairGuide.background4": "default",
      "editorBracketPairGuide.background5": "default",
      "editorBracketPairGuide.background6": "default",
      "editorCodeLens.foreground": fg,
      "editorCommentsWidget.rangeActiveBackground": bg,
      "editorCommentsWidget.rangeBackground": bg,
      "editorCommentsWidget.replyInputBackground": bg,
      "editorCommentsWidget.resolvedBorder": "default",
      "editorCommentsWidget.unresolvedBorder": "default",
      "editorCursor.background": bg,
      "editorCursor.foreground": fg,
      "editorError.background": bg,
      "editorError.border": fg_ta,
      "editorError.foreground": fg,
      "editorGhostText.background": bg,
      "editorGhostText.border": "default",
      "editorGhostText.foreground": fg,
      "editorGroup.border": fg_ta,
      "editorGroup.dropBackground": fg_tb,
      "editorGroup.dropIntoPromptBackground": bg,
      "editorGroup.dropIntoPromptBorder": "default",
      "editorGroup.dropIntoPromptForeground": fg,
      "editorGroup.emptyBackground": bg,
      "editorGroup.focusedEmptyBorder": fg_ta,
      "editorGroupHeader.border": fg_ta,
      "editorGroupHeader.noTabsBackground": bg,
      "editorGroupHeader.tabsBackground": bg,
      "editorGroupHeader.tabsBorder": fg_ta,
      "editorGutter.addedBackground": fg_tb,
      "editorGutter.background": bg,
      "editorGutter.commentGlyphForeground": fg,
      "editorGutter.commentRangeForeground": fg_tb,
      "editorGutter.commentUnresolvedGlyphForeground": fg,
      "editorGutter.deletedBackground": fg_tb,
      "editorGutter.foldingControlForeground": fg_ta,
      "editorGutter.modifiedBackground": fg_tb,
      "editorHint.border": fg_ta,
      "editorHint.foreground": fg,
      "editorHoverWidget.background": fg_sb,
      "editorHoverWidget.border": fg_ta,
      "editorHoverWidget.foreground": fg,
      "editorHoverWidget.highlightForeground": fg,
      "editorHoverWidget.statusBarBackground": fg_tb,
      "editorIndentGuide.activeBackground1": fg_tb,
      "editorIndentGuide.activeBackground2": fg_tb,
      "editorIndentGuide.activeBackground3": fg_tb,
      "editorIndentGuide.activeBackground4": fg_tb,
      "editorIndentGuide.activeBackground5": fg_tb,
      "editorIndentGuide.activeBackground6": fg_tb,
      "editorIndentGuide.background1": fg_tc,
      "editorIndentGuide.background2": fg_tc,
      "editorIndentGuide.background3": fg_tc,
      "editorIndentGuide.background4": fg_tc,
      "editorIndentGuide.background5": fg_tc,
      "editorIndentGuide.background6": fg_tc,
      "editorInfo.background": bg,
      "editorInfo.border": fg_ta,
      "editorInfo.foreground": fg,
      "editorInlayHint.background": bg,
      "editorInlayHint.foreground": fg,
      "editorInlayHint.parameterBackground": bg,
      "editorInlayHint.parameterForeground": fg,
      "editorInlayHint.typeBackground": bg,
      "editorInlayHint.typeForeground": fg,
      "editorLightBulb.foreground": fg_ta,
      "editorLightBulbAi.foreground": fg,
      "editorLightBulbAutoFix.foreground": fg_ta,
      "editorLineNumber.activeForeground": fg,
      "editorLineNumber.dimmedForeground": fg,
      "editorLineNumber.foreground": fg_tb,
      "editorLink.activeForeground": fg,
      "editorMarkerNavigation.background": fg_tb,
      "editorMarkerNavigationError.background": fg_tb,
      "editorMarkerNavigationError.headerBackground": bg,
      "editorMarkerNavigationInfo.background": fg_tb,
      "editorMarkerNavigationInfo.headerBackground": bg,
      "editorMarkerNavigationWarning.background": fg_tb,
      "editorMarkerNavigationWarning.headerBackground": bg,
      "editorMinimap.inlineChatInserted": "default",
      "editorMultiCursor.primary.background": bg,
      "editorMultiCursor.primary.foreground": fg,
      "editorMultiCursor.secondary.background": bg,
      "editorMultiCursor.secondary.foreground": fg,
      "editorOverviewRuler.addedForeground": fg_tb,
      "editorOverviewRuler.background": bg,
      "editorOverviewRuler.border": fg_ta,
      "editorOverviewRuler.bracketMatchForeground": fg_tb,
      "editorOverviewRuler.commentForeground": fg,
      "editorOverviewRuler.commentUnresolvedForeground": fg,
      "editorOverviewRuler.commonContentForeground": fg_tb,
      "editorOverviewRuler.currentContentForeground": fg_tb,
      "editorOverviewRuler.deletedForeground": fg_tb,
      "editorOverviewRuler.errorForeground": fg_ta,
      "editorOverviewRuler.findMatchForeground": fg_tb,
      "editorOverviewRuler.incomingContentForeground": fg_tb,
      "editorOverviewRuler.infoForeground": fg_tb,
      "editorOverviewRuler.inlineChatInserted": "default",
      "editorOverviewRuler.inlineChatRemoved": "default",
      "editorOverviewRuler.modifiedForeground": fg_tb,
      "editorOverviewRuler.rangeHighlightForeground": fg_tb,
      "editorOverviewRuler.selectionHighlightForeground": fg_tb,
      "editorOverviewRuler.warningForeground": fg_tb,
      "editorOverviewRuler.wordHighlightForeground": fg_tb,
      "editorOverviewRuler.wordHighlightStrongForeground": fg_tb,
      "editorOverviewRuler.wordHighlightTextForeground": fg,
      "editorPane.background": fg_tb,
      "editorRuler.foreground": fg,
      "editorStickyScroll.background": bg,
      "editorStickyScroll.border": "default",
      "editorStickyScroll.shadow": "default",
      "editorStickyScrollHover.background": bg,
      "editorSuggestWidget.background": bg,
      "editorSuggestWidget.border": fg_ta,
      "editorSuggestWidget.focusHighlightForeground": fg,
      "editorSuggestWidget.foreground": fg,
      "editorSuggestWidget.highlightForeground": fg,
      "editorSuggestWidget.selectedBackground": fg_ta,
      "editorSuggestWidget.selectedForeground": fg,
      "editorSuggestWidget.selectedIconForeground": fg,
      "editorSuggestWidgetStatus.foreground": fg,
      "editorUnicodeHighlight.background": bg,
      "editorUnicodeHighlight.border": "default",
      "editorUnnecessaryCode.border": fg_ta,
      "editorUnnecessaryCode.opacity": fg_tb,
      "editorWarning.background": bg,
      "editorWarning.border": fg_ta,
      "editorWarning.foreground": fg,
      "editorWatermark.foreground": fg,
      "editorWhitespace.foreground": fg_tb,
      "editorWidget.background": bg,
      "editorWidget.border": fg_ta,
      "editorWidget.foreground": fg,
      "editorWidget.resizeBorder": fg_ta,
      "errorForeground": fg,
      "extensionBadge.remoteBackground": bg,
      "extensionBadge.remoteForeground": fg,
      "extensionButton.background": bg,
      "extensionButton.foreground": fg,
      "extensionButton.hoverBackground": bg,
      "extensionButton.prominentBackground": bg,
      "extensionButton.prominentForeground": fg,
      "extensionButton.prominentHoverBackground": bg,
      "extensionButton.separator": "default",
      "extensionIcon.preReleaseForeground": fg,
      "extensionIcon.sponsorForeground": fg,
      "extensionIcon.starForeground": fg,
      "extensionIcon.verifiedForeground": fg,
      "focusBorder": fg_ta,
      "foreground": fg,
      "git.blame.editorDecorationForeground": fg,
      "gitDecoration.addedResourceForeground": fg,
      "gitDecoration.conflictingResourceForeground": fg,
      "gitDecoration.deletedResourceForeground": fg,
      "gitDecoration.ignoredResourceForeground": fg_ta,
      "gitDecoration.modifiedResourceForeground": fg,
      "gitDecoration.renamedResourceForeground": fg,
      "gitDecoration.stageDeletedResourceForeground": fg,
      "gitDecoration.stageModifiedResourceForeground": fg,
      "gitDecoration.submoduleResourceForeground": fg,
      "gitDecoration.untrackedResourceForeground": fg,
      "icon.foreground": fg,
      "inlineChat.background": bg,
      "inlineChat.border": "default",
      "inlineChat.foreground": fg,
      "inlineChat.shadow": "default",
      "inlineChatDiff.inserted": "default",
      "inlineChatDiff.removed": "default",
      "inlineChatInput.background": bg,
      "inlineChatInput.border": "default",
      "inlineChatInput.focusBorder": "default",
      "inlineChatInput.placeholderForeground": fg,
      "inlineEdit.gutterIndicator.background": bg,
      "inlineEdit.gutterIndicator.primaryBackground": bg,
      "inlineEdit.gutterIndicator.primaryForeground": fg,
      "inlineEdit.gutterIndicator.secondaryBackground": bg,
      "inlineEdit.gutterIndicator.secondaryForeground": fg,
      "inlineEdit.gutterIndicator.successfulBackground": bg,
      "inlineEdit.gutterIndicator.successfulForeground": fg,
      "inlineEdit.indicator.background": bg,
      "inlineEdit.indicator.border": "default",
      "inlineEdit.indicator.foreground": fg,
      "inlineEdit.modifiedBackground": bg,
      "inlineEdit.modifiedBorder": "default",
      "inlineEdit.modifiedChangedLineBackground": bg,
      "inlineEdit.modifiedChangedTextBackground": bg,
      "inlineEdit.originalBackground": bg,
      "inlineEdit.originalBorder": "default",
      "inlineEdit.originalChangedLineBackground": bg,
      "inlineEdit.originalChangedTextBackground": bg,
      "inlineEdit.wordReplacementView.background": bg,
      "input.background": bg,
      "input.border": fg_ta,
      "input.foreground": fg,
      "input.placeholderForeground": fg_ta,
      "inputOption.activeBackground": fg_tb,
      "inputOption.activeBorder": fg_ta,
      "inputOption.activeForeground": fg_ta,
      "inputOption.hoverBackground": bg,
      "inputValidation.errorBackground": bg,
      "inputValidation.errorBorder": fg_ta,
      "inputValidation.errorForeground": fg,
      "inputValidation.infoBackground": bg,
      "inputValidation.infoBorder": fg_ta,
      "inputValidation.infoForeground": fg,
      "inputValidation.warningBackground": bg,
      "inputValidation.warningBorder": fg_ta,
      "inputValidation.warningForeground": fg,
      "interactive.activeCodeBorder": "default",
      "interactive.inactiveCodeBorder": "default",
      "issues.closed": "default",
      "issues.newIssueDecoration": "default",
      "issues.open": "default",
      "keybindingLabel.background": bg,
      "keybindingLabel.border": "default",
      "keybindingLabel.bottomBorder": "default",
      "keybindingLabel.foreground": fg,
      "keybindingTable.headerBackground": bg,
      "keybindingTable.rowsBackground": bg,
      "list.activeSelectionBackground": fg,
      "list.activeSelectionForeground": bg,
      "list.activeSelectionIconForeground": fg,
      "list.deemphasizedForeground": fg_ta,
      "list.dropBackground": fg_tb,
      "list.dropBetweenBackground": bg,
      "list.errorForeground": fg,
      "list.filterMatchBackground": bg,
      "list.filterMatchBorder": fg_ta,
      "list.focusAndSelectionOutline": "default",
      "list.focusBackground": fg_ta,
      "list.focusForeground": fg,
      "list.focusHighlightForeground": fg,
      "list.focusOutline": "default",
      "list.highlightForeground": fg,
      "list.hoverBackground": fg_ta,
      "list.hoverForeground": fg,
      "list.inactiveFocusBackground": fg_tb,
      "list.inactiveFocusOutline": "default",
      "list.inactiveSelectionBackground": fg_tb,
      "list.inactiveSelectionForeground": fg,
      "list.inactiveSelectionIconForeground": fg,
      "list.invalidItemForeground": fg,
      "list.warningForeground": fg,
      "listFilterWidget.background": bg,
      "listFilterWidget.noMatchesOutline": fg_ta,
      "listFilterWidget.outline": fg,
      "listFilterWidget.shadow": "default",
      "menu.background": bg,
      "menu.border": fg_ta,
      "menu.foreground": fg,
      "menu.selectionBackground": fg_ta,
      "menu.selectionBorder": fg_ta,
      "menu.selectionForeground": bg,
      "menu.separatorBackground": fg_ta,
      "menubar.selectionBackground": fg_tb,
      "menubar.selectionBorder": fg_ta,
      "menubar.selectionForeground": fg,
      "merge.border": fg_ta,
      "merge.commonContentBackground": fg_tb,
      "merge.commonHeaderBackground": fg_tb,
      "merge.currentContentBackground": fg_tb,
      "merge.currentHeaderBackground": fg_tb,
      "merge.incomingContentBackground": fg_tb,
      "merge.incomingHeaderBackground": fg_tb,
      "mergeEditor.change.background": bg,
      "mergeEditor.change.word.background": bg,
      "mergeEditor.changeBase.background": bg,
      "mergeEditor.changeBase.word.background": bg,
      "mergeEditor.conflict.handled.minimapOverViewRuler": "default",
      "mergeEditor.conflict.handledFocused.border": "default",
      "mergeEditor.conflict.handledUnfocused.border": "default",
      "mergeEditor.conflict.input1.background": bg,
      "mergeEditor.conflict.input2.background": bg,
      "mergeEditor.conflict.unhandled.minimapOverViewRuler": "default",
      "mergeEditor.conflict.unhandledFocused.border": "default",
      "mergeEditor.conflict.unhandledUnfocused.border": "default",
      "mergeEditor.conflictingLines.background": bg,
      "minimap.background": bg,
      "minimap.errorHighlight": fg_ta,
      "minimap.findMatchHighlight": fg_ta,
      "minimap.foregroundOpacity": "default",
      "minimap.infoHighlight": "default",
      "minimap.selectionHighlight": fg_ta,
      "minimap.selectionOccurrenceHighlight": "default",
      "minimap.warningHighlight": fg_ta,
      "minimapGutter.addedBackground": fg_tb,
      "minimapGutter.deletedBackground": fg_tb,
      "minimapGutter.modifiedBackground": fg_tb,
      "minimapSlider.activeBackground": fg_tb,
      "minimapSlider.background": fg_tc,
      "minimapSlider.hoverBackground": fg_tc,
      "multiDiffEditor.background": bg,
      "multiDiffEditor.border": "default",
      "multiDiffEditor.headerBackground": bg,
      "notebook.cellBorderColor": fg_ta,
      "notebook.cellEditorBackground": bg,
      "notebook.cellHoverBackground": bg,
      "notebook.cellInsertionIndicator": "default",
      "notebook.cellStatusBarItemHoverBackground": fg_tc,
      "notebook.cellToolbarSeparator": fg_ta,
      "notebook.editorBackground": bg,
      "notebook.focusedCellBackground": bg,
      "notebook.focusedCellBorder": "default",
      "notebook.focusedEditorBorder": "default",
      "notebook.inactiveFocusedCellBorder": "default",
      "notebook.inactiveSelectedCellBorder": "default",
      "notebook.outputContainerBackgroundColor": bg,
      "notebook.outputContainerBorderColor": "default",
      "notebook.selectedCellBackground": bg,
      "notebook.selectedCellBorder": "default",
      "notebook.symbolHighlightBackground": bg,
      "notebookEditorOverviewRuler.runningCellForeground": fg,
      "notebookScrollbarSlider.activeBackground": bg,
      "notebookScrollbarSlider.background": bg,
      "notebookScrollbarSlider.hoverBackground": bg,
      "notebookStatusErrorIcon.foreground": "#ff0000",
      "notebookStatusRunningIcon.foreground": "#ff0000",
      "notebookStatusSuccessIcon.foreground": "#ff0000",
      "notificationCenter.border": fg_ta,
      "notificationCenterHeader.background": bg,
      "notificationCenterHeader.foreground": fg,
      "notificationLink.foreground": fg,
      "notifications.background": bg,
      "notifications.border": fg_ta,
      "notifications.foreground": fg,
      "notificationsErrorIcon.foreground": fg,
      "notificationsInfoIcon.foreground": fg,
      "notificationsWarningIcon.foreground": fg,
      "notificationToast.border": fg_ta,
      "outputView.background": bg,
      "outputViewStickyScroll.background": bg,
      "panel.background": bg,
      "panel.border": fg_ta,
      "panel.dropBorder": fg,
      "panelInput.border": fg_ta,
      "panelSection.border": fg_ta,
      "panelSection.dropBackground": fg_tc,
      "panelSectionHeader.background": bg,
      "panelSectionHeader.border": fg_ta,
      "panelSectionHeader.foreground": fg,
      "panelStickyScroll.background": bg,
      "panelStickyScroll.border": "default",
      "panelStickyScroll.shadow": "default",
      "panelTitle.activeBorder": fg_ta,
      "panelTitle.activeForeground": fg,
      "panelTitle.border": "default",
      "panelTitle.inactiveForeground": fg_ta,
      "peekView.border": fg_ta,
      "peekViewEditor.background": bg,
      "peekViewEditor.matchHighlightBackground": bg,
      "peekViewEditor.matchHighlightBorder": fg_ta,
      "peekViewEditorGutter.background": bg,
      "peekViewEditorStickyScroll.background": bg,
      "peekViewResult.background": bg,
      "peekViewResult.fileForeground": fg,
      "peekViewResult.lineForeground": fg,
      "peekViewResult.matchHighlightBackground": bg,
      "peekViewResult.selectionBackground": bg,
      "peekViewResult.selectionForeground": fg,
      "peekViewTitle.background": bg,
      "peekViewTitleDescription.foreground": fg,
      "peekViewTitleLabel.foreground": fg,
      "pickerGroup.border": fg_ta,
      "pickerGroup.foreground": fg,
      "ports.iconRunningProcessForeground": fg,
      "problemsErrorIcon.foreground": fg,
      "problemsInfoIcon.foreground": fg,
      "problemsWarningIcon.foreground": fg,
      "profileBadge.background": bg,
      "profileBadge.foreground": fg,
      "profiles.sashBorder": "default",
      "progressBar.background": fg_ta,
      "pullRequests.closed": "default",
      "pullRequests.draft": "default",
      "pullRequests.merged": "default",
      "pullRequests.notification": "default",
      "pullRequests.open": "default",
      "quickInput.background": bg,
      "quickInput.foreground": fg,
      "quickInput.list.focusBackground": bg,
      "quickInputList.focusBackground": bg,
      "quickInputList.focusForeground": fg,
      "quickInputList.focusIconForeground": fg,
      "quickInputTitle.background": bg,
      "radio.activeBackground": bg,
      "radio.activeBorder": "default",
      "radio.activeForeground": fg,
      "radio.inactiveBackground": bg,
      "radio.inactiveBorder": "default",
      "radio.inactiveForeground": fg,
      "radio.inactiveHoverBackground": bg,
      "sash.hoverBorder": "default",
      "scmGraph.foreground1": "default",
      "scmGraph.foreground2": "default",
      "scmGraph.foreground3": "default",
      "scmGraph.foreground4": "default",
      "scmGraph.foreground5": "default",
      "scmGraph.historyItemBaseRefColor": "default",
      "scmGraph.historyItemHoverAdditionsForeground": fg,
      "scmGraph.historyItemHoverDefaultLabelBackground": bg,
      "scmGraph.historyItemHoverDefaultLabelForeground": fg,
      "scmGraph.historyItemHoverDeletionsForeground": fg,
      "scmGraph.historyItemHoverLabelForeground": fg,
      "scmGraph.historyItemRefColor": "default",
      "scmGraph.historyItemRemoteRefColor": "default",
      "scrollbar.shadow": fg_tb,
      "scrollbarSlider.activeBackground": fg_tb,
      "scrollbarSlider.background": fg_tb,
      "scrollbarSlider.hoverBackground": fg_tb,
      "search.resultsInfoForeground": fg,
      "searchEditor.findMatchBackground": bg,
      "searchEditor.findMatchBorder": fg_ta,
      "searchEditor.textInputBorder": fg_ta,
      "selection.background": fg_ta,
      "settings.checkboxBackground": bg,
      "settings.checkboxBorder": fg_ta,
      "settings.checkboxForeground": fg,
      "settings.dropdownBackground": bg,
      "settings.dropdownBorder": fg_ta,
      "settings.dropdownForeground": fg,
      "settings.dropdownListBorder": fg_ta,
      "settings.focusedRowBackground": bg,
      "settings.focusedRowBorder": "default",
      "settings.headerBorder": "default",
      "settings.headerForeground": fg,
      "settings.modifiedItemIndicator": fg_ta,
      "settings.numberInputBackground": bg,
      "settings.numberInputBorder": fg_ta,
      "settings.numberInputForeground": fg,
      "settings.rowHoverBackground": bg,
      "settings.sashBorder": "default",
      "settings.settingsHeaderHoverForeground": fg,
      "settings.textInputBackground": bg,
      "settings.textInputBorder": fg_ta,
      "settings.textInputForeground": fg,
      "sideBar.background": bg,
      "sideBar.border": fg_ta,
      "sideBar.dropBackground": fg_tb,
      "sideBar.foreground": fg,
      "sideBarActivityBarTop.border": "default",
      "sideBarSectionHeader.background": fg_tb,
      "sideBarSectionHeader.border": fg_ta,
      "sideBarSectionHeader.foreground": fg,
      "sideBarStickyScroll.background": bg,
      "sideBarStickyScroll.border": "default",
      "sideBarStickyScroll.shadow": "default",
      "sideBarTitle.background": bg,
      "sideBarTitle.border": "default",
      "sideBarTitle.foreground": fg,
      "sideBySideEditor.horizontalBorder": "default",
      "sideBySideEditor.verticalBorder": "default",
      "simpleFindWidget.sashBorder": "default",
      "statusBar.background": fg_tb,
      "statusBar.border": fg_ta,
      "statusBar.debuggingBackground": fg,
      "statusBar.debuggingBorder": fg_ta,
      "statusBar.debuggingForeground": bg,
      "statusBar.focusBorder": "default",
      "statusBar.foreground": fg,
      "statusBar.noFolderBackground": bg,
      "statusBar.noFolderBorder": fg_ta,
      "statusBar.noFolderForeground": fg,
      "statusBarItem.activeBackground": bg,
      "statusBarItem.compactHoverBackground": bg,
      "statusBarItem.errorBackground": bg,
      "statusBarItem.errorForeground": fg,
      "statusBarItem.errorHoverBackground": bg,
      "statusBarItem.errorHoverForeground": fg,
      "statusBarItem.focusBorder": "default",
      "statusBarItem.hoverBackground": bg,
      "statusBarItem.hoverForeground": fg,
      "statusBarItem.offlineBackground": bg,
      "statusBarItem.offlineForeground": fg,
      "statusBarItem.offlineHoverBackground": bg,
      "statusBarItem.offlineHoverForeground": fg,
      "statusBarItem.prominentBackground": bg,
      "statusBarItem.prominentForeground": fg,
      "statusBarItem.prominentHoverBackground": bg,
      "statusBarItem.prominentHoverForeground": fg,
      "statusBarItem.remoteBackground": bg,
      "statusBarItem.remoteForeground": fg,
      "statusBarItem.remoteHoverBackground": bg,
      "statusBarItem.remoteHoverForeground": fg,
      "statusBarItem.warningBackground": bg,
      "statusBarItem.warningForeground": fg,
      "statusBarItem.warningHoverBackground": bg,
      "statusBarItem.warningHoverForeground": fg,
      "symbolIcon.arrayForeground": fg,
      "symbolIcon.booleanForeground": fg,
      "symbolIcon.classForeground": fg,
      "symbolIcon.colorForeground": fg,
      "symbolIcon.constantForeground": fg,
      "symbolIcon.constructorForeground": fg,
      "symbolIcon.enumeratorForeground": fg,
      "symbolIcon.enumeratorMemberForeground": fg,
      "symbolIcon.eventForeground": fg,
      "symbolIcon.fieldForeground": fg,
      "symbolIcon.fileForeground": fg,
      "symbolIcon.folderForeground": fg,
      "symbolIcon.functionForeground": fg,
      "symbolIcon.interfaceForeground": fg,
      "symbolIcon.keyForeground": fg,
      "symbolIcon.keywordForeground": fg,
      "symbolIcon.methodForeground": fg,
      "symbolIcon.moduleForeground": fg,
      "symbolIcon.namespaceForeground": fg,
      "symbolIcon.nullForeground": fg,
      "symbolIcon.numberForeground": fg,
      "symbolIcon.objectForeground": fg,
      "symbolIcon.operatorForeground": fg,
      "symbolIcon.packageForeground": fg,
      "symbolIcon.propertyForeground": fg,
      "symbolIcon.referenceForeground": fg,
      "symbolIcon.snippetForeground": fg,
      "symbolIcon.stringForeground": fg,
      "symbolIcon.structForeground": fg,
      "symbolIcon.textForeground": fg,
      "symbolIcon.typeParameterForeground": fg,
      "symbolIcon.unitForeground": fg,
      "symbolIcon.variableForeground": fg,
      "tab.activeBackground": fg_tb,
      "tab.activeBorder": bg,
      "tab.activeBorderTop": bg,
      "tab.activeForeground": fg,
      "tab.activeModifiedBorder": fg_ta,
      "tab.border": bg,
      "tab.dragAndDropBorder": "default",
      "tab.hoverBackground": fg_tb,
      "tab.hoverBorder": fg_ta,
      "tab.hoverForeground": fg_ta,
      "tab.inactiveBackground": bg,
      "tab.inactiveForeground": fg_ta,
      "tab.inactiveModifiedBorder": bg,
      "tab.lastPinnedBorder": "default",
      "tab.selectedBackground": bg,
      "tab.selectedBorderTop": "default",
      "tab.selectedForeground": fg,
      "tab.unfocusedActiveBackground": fg_tb,
      "tab.unfocusedActiveBorder": bg,
      "tab.unfocusedActiveBorderTop": bg,
      "tab.unfocusedActiveForeground": fg,
      "tab.unfocusedActiveModifiedBorder": bg,
      "tab.unfocusedHoverBackground": fg_tb,
      "tab.unfocusedHoverBorder": bg,
      "tab.unfocusedHoverForeground": fg_tb,
      "tab.unfocusedInactiveBackground": bg,
      "tab.unfocusedInactiveForeground": fg_ta,
      "tab.unfocusedInactiveModifiedBorder": bg,
      "terminal.ansiBlack": fgc.s0,
      "terminal.ansiBlue": fgc.s1,
      "terminal.ansiBrightBlack": fgc.s0,
      "terminal.ansiBrightBlue": fgc.s1,
      "terminal.ansiBrightCyan": fgc.s5,
      "terminal.ansiBrightGreen": fgc.s3,
      "terminal.ansiBrightMagenta": fgc.s2,
      "terminal.ansiBrightRed": fgc.s4,
      "terminal.ansiBrightWhite": fgc.s7,
      "terminal.ansiBrightYellow": fgc.s6,
      "terminal.ansiCyan": fgc.s5,
      "terminal.ansiGreen": fgc.s3,
      "terminal.ansiMagenta": fgc.s2,
      "terminal.ansiRed": fgc.s4,
      "terminal.ansiWhite": fgc.s7,
      "terminal.ansiYellow": fgc.s6,
      "terminal.background": bg,
      "terminal.border": fg_ta,
      "terminal.dropBackground": bg,
      "terminal.findMatchBackground": bg,
      "terminal.findMatchBorder": "default",
      "terminal.findMatchHighlightBackground": bg,
      "terminal.findMatchHighlightBorder": "default",
      "terminal.foreground": fg,
      "terminal.hoverHighlightBackground": bg,
      "terminal.inactiveSelectionBackground": bg,
      "terminal.initialHintForeground": fg,
      "terminal.selectionBackground": fg_tb,
      "terminal.selectionForeground": fg,
      "terminal.tab.activeBorder": "default",
      "terminalCommandDecoration.defaultBackground": bg,
      "terminalCommandDecoration.errorBackground": bg,
      "terminalCommandDecoration.successBackground": bg,
      "terminalCommandGuide.foreground": fg,
      "terminalCursor.background": bg,
      "terminalCursor.foreground": fg,
      "terminalOverviewRuler.border": "default",
      "terminalOverviewRuler.cursorForeground": fg,
      "terminalOverviewRuler.findMatchForeground": fg,
      "terminalStickyScroll.background": bg,
      "terminalStickyScroll.border": "default",
      "terminalStickyScrollHover.background": bg,
      "testing.coverCountBadgeBackground": bg,
      "testing.coverCountBadgeForeground": fg,
      "testing.coveredBackground": bg,
      "testing.coveredBorder": "default",
      "testing.coveredGutterBackground": bg,
      "testing.iconErrored.retired": "default",
      "testing.iconErrored": "default",
      "testing.iconFailed.retired": "default",
      "testing.iconFailed": "default",
      "testing.iconPassed.retired": "default",
      "testing.iconPassed": "default",
      "testing.iconQueued.retired": "default",
      "testing.iconQueued": "default",
      "testing.iconSkipped.retired": "default",
      "testing.iconSkipped": "default",
      "testing.iconUnset.retired": "default",
      "testing.iconUnset": "default",
      "testing.message.error.badgeBackground": bg,
      "testing.message.error.badgeBorder": "default",
      "testing.message.error.badgeForeground": fg,
      "testing.message.error.lineBackground": bg,
      "testing.message.info.decorationForeground": fg,
      "testing.message.info.lineBackground": bg,
      "testing.messagePeekBorder": "default",
      "testing.messagePeekHeaderBackground": bg,
      "testing.peekBorder": "default",
      "testing.peekHeaderBackground": bg,
      "testing.runAction": "default",
      "testing.uncoveredBackground": bg,
      "testing.uncoveredBorder": "default",
      "testing.uncoveredBranchBackground": bg,
      "testing.uncoveredGutterBackground": bg,
      "textBlockQuote.background": bg,
      "textBlockQuote.border": fg_ta,
      "textCodeBlock.background": bg,
      "textLink.activeForeground": fg,
      "textLink.foreground": fg_ta,
      "textPreformat.background": bg,
      "textPreformat.foreground": fg,
      "textSeparator.foreground": fg,
      "titleBar.activeBackground": bg,
      "titleBar.activeForeground": fg,
      "titleBar.border": fg_ta,
      "titleBar.inactiveBackground": bg,
      "titleBar.inactiveForeground": fg,
      "toolbar.activeBackground": bg,
      "toolbar.hoverBackground": bg,
      "toolbar.hoverOutline": "default",
      "tree.inactiveIndentGuidesStroke": "default",
      "tree.indentGuidesStroke": fg_ta,
      "tree.tableColumnsBorder": "default",
      "tree.tableOddRowsBackground": bg,
      "walkThrough.embeddedEditorBackground": bg,
      "walkthrough.stepTitle.foreground": fg,
      "welcomePage.background": bg,
      "welcomePage.buttonBackground": bg,
      "welcomePage.buttonHoverBackground": bg,
      "welcomePage.progress.background": bg,
      "welcomePage.progress.foreground": fg,
      "welcomePage.tileBackground": bg,
      "welcomePage.tileBorder": "default",
      "welcomePage.tileHoverBackground": bg,
      "widget.border": "default",
      "widget.shadow": fg_tb,
      "window.activeBorder": fg_ta,
      "window.inactiveBorder": fg_tb,
    },
    tokenColors: [
      {
        scope: ["comment"],
        settings: {
          foreground: fg_tb,
        },
      },
      {
        scope: ["keyword", "storage"],
        settings: {
          foreground: fg_ta,
        },
      },
      {
        scope: ["entity", "strong"],
        settings: {
          fontStyle: "bold",
        },
      },
      {
        scope: ["invalid"],
        settings: {
          foreground: fg_ta,
          fontStyle: "italic underline",
        },
      },
    ],
    "semanticHighlighting": false,
    "semanticTokenColors": {
    }
  };
};

module.exports = {
  opaque,
  opaqueRgb,
  rgbaArrayToStr,
  rgbaStrToArray,
  crtTemplate,
};
