/**
 * Compute the opaque color from a foreground color with alpha channel against at solid color background.
 *
 * We need the ability to compute the same opaque foreground color as the transparent
 * version with a formula.
 *
 * https://graphicdesign.stackexchange.com/questions/113007/how-to-determine-the-equivalent-opaque-rgb-color-for-a-given-partially-transpare
 * https://stackoverflow.com/questions/15898740/how-to-convert-rgba-to-a-transparency-adjusted-hex
 *
 * @param {number[]} rgba
 * @param {number[]} brgb
 * @returns {number[]} the solid color
 */

const opaque = (rgba, brgb) => {
  // Color = Color * alpha + Background * (1 - alpha);
  let ret = new Array(4);
  let alpha = rgba[3];
  ret[3] = 1;

  for (i = 0; i < 3; i++) {
    ret[i] = Math.round(rgba[i] * alpha + brgb[i] * (1 - alpha));
  }

  return ret;
};

/**
 * Compute the opaque color from a foreground with alpha and solid background.
 *
 * @param {string} rgba (#rgba or #rrggbbaa)
 * @param {string} brgb (#rgb or #rrggbb)
 *
 * @returns {string} the solid color
 */

const opaqueRgb = (rgba, brgb) => {
  return rgbaArrayToStr(opaque(rgbaStrToArray(rgba), rgbaStrToArray(brgb)));
};

/**
 * Split a hex rgba-value (#rrggbbaa or #rgba).
 *
 * @param {string} rgba
 * @returns {number[]} rgba array
 */
const rgbaStrToArray = (rgba) => {
  let ret = new Array(4);

  const p1 = () => {
    ret[0] = parseInt(rgba[1] + rgba[1], 16);
    ret[1] = parseInt(rgba[2] + rgba[2], 16);
    ret[2] = parseInt(rgba[3] + rgba[3], 16);
  };

  const p2 = () => {
    ret[0] = parseInt(rgba[1] + rgba[2], 16);
    ret[1] = parseInt(rgba[3] + rgba[4], 16);
    ret[2] = parseInt(rgba[5] + rgba[6], 16);
  };

  if (rgba.length === 4) {
    // #rgb
    p1();
    ret[3] = 1;
  } else if (rgba.length === 5) {
    // #rgba
    p1();
    ret[3] = parseInt(rgba[4] + rgba[4], 16) / 0xff;
  } else if (rgba.length === 7) {
    // #rrggbb
    p2();
    ret[3] = 1;
  } else if (rgba.length === 9) {
    // #rrggbbaa
    p2();
    ret[3] = parseInt(rgba[7] + rgba[8], 16) / 0xff;
  }

  return ret;
};

/**
 * Join rgba-array.
 *
 * @param {number[]} rgba
 * @returns {string} rgba string
 */
const rgbaArrayToStr = (rgba) => {
  return (
    "#" +
    rgba
      .map(function (x, i) {
        let y = "0";
        if (i < 3) {
          y += x.toString(16);
        } else {
          y += Math.round(x * 0xff).toString(16);
        }
        return y.slice(-2);
      })
      .join("")
  );
};

/**
 * Create a CRT Theme programmatically. Serialize into json for inclusion
 * in theme extension.
 *
 * @param {string} name the name of the template
 * @param {string} type of template (dark, light, hc)
 * @param {string} foreground foreground color (#rrggbb)
 * @param {string} background background color (#rrggbb)
 * @param {string[]} opacityLevels array of up to 16 opacities as hex strings "00" to "ff" to override defaults
 * @param {object} template template object with all possible color attributes
 *
 * @returns {any} the resulting template
 */

const crtTemplate = (name, type, foreground, background, opacityLevels, template) => {
  // Default levels of opacity
  const defaultOpacityLevels = [];
  for (let i = 0; i < 16; i++) {
    let y = "0";
    y += Math.round(0xff - (i * 0xff) / 15).toString(16);
    defaultOpacityLevels[i] = y.slice(-2);
  }

  // Override levels of opacity
  if (opacityLevels) {
    for (let i = 0; i < opacityLevels.length; i++) {
      defaultOpacityLevels[i] = opacityLevels[i];
    }
  }

  const foregroundColors = {};

  for (let i = 0; i < defaultOpacityLevels.length; i++) {
    foregroundColors["t" + i] = foreground + defaultOpacityLevels[i];               // Transparent color
    foregroundColors["s" + i] = opaqueRgb(foregroundColors["t" + i], background);   // Solid color looking like corresponding transparent
  }

  // Basic colors to use everywhere
  let fg_ta = foregroundColors.t7, //fg_sa = fgc.s7,
    fg_tb = foregroundColors.t12,
    fg_sb = foregroundColors.s12,
    fg_tc = foregroundColors.t14; // fg_sc = fgc.s14;

  // Logical colors
  let activeBackground = fg_ta,
    inactiveForeground = fg_tb
  ;

  return {
    "$schema": "vscode://schemas/color-theme",
    name: name,
    type: type,
    colors: {
      "actionBar.toggledBackground": fg_ta,
      "activityBar.activeBackground": activeBackground,
      "activityBar.activeBorder": fg_ta,
      "activityBar.activeFocusBorder": fg_ta,
      "activityBar.background": background,
      "activityBar.border": fg_ta,
      "activityBar.dropBorder": fg_ta,
      "activityBar.foreground": foreground,
      "activityBar.inactiveForeground": inactiveForeground,
      "activityBarBadge.background": foreground,
      "activityBarBadge.foreground": background,
      "activityBarTop.activeBackground": activeBackground,
      "activityBarTop.activeBorder": fg_ta,
      "activityBarTop.background": background,
      "activityBarTop.dropBorder": fg_ta,
      "activityBarTop.foreground": foreground,
      "activityBarTop.inactiveForeground": inactiveForeground,
      "activityErrorBadge.background": foreground,
      "activityErrorBadge.foreground": background,
      "activityWarningBadge.background": foreground,
      "activityWarningBadge.foreground": background,
      "badge.background": background,
      "badge.foreground": foreground,
      "banner.background": background,
      "banner.foreground": foreground,
      "banner.iconForeground": foreground,
      "breadcrumb.activeSelectionForeground": foreground,
      "breadcrumb.background": background,
      "breadcrumb.focusForeground": foreground,
      "breadcrumb.foreground": fg_ta,
      "breadcrumbPicker.background": background,
      "button.background": background,
      "button.border": "default",
      "button.foreground": foreground,
      "button.hoverBackground": fg_ta,
      "button.secondaryBackground": background,
      "button.secondaryForeground": foreground,
      "button.secondaryHoverBackground": background,
      "button.separator": foreground,
      "chart.axis": foreground,
      "chart.guide": foreground,
      "chart.line": foreground,
      "charts.blue": fg_tb,
      "charts.foreground": foreground,
      "charts.green": fg_tb,
      "charts.lines": fg_ta,
      "charts.orange": fg_tb,
      "charts.purple": fg_tb,
      "charts.red": fg_tb,
      "charts.yellow": fg_tb,
      "chat.avatarBackground": background,
      "chat.avatarForeground": foreground,
      "chat.editedFileForeground": foreground,
      "chat.requestBackground": background,
      "chat.requestBorder": foreground,
      "chat.slashCommandBackground": background,
      "chat.slashCommandForeground": foreground,
      "checkbox.background": background,
      "checkbox.border": fg_ta,
      "checkbox.foreground": foreground,
      "checkbox.selectBackground": background,
      "checkbox.selectBorder": foreground,
      "commandCenter.activeBackground": activeBackground,
      "commandCenter.activeBorder": foreground,
      "commandCenter.activeForeground": foreground,
      "commandCenter.background": background,
      "commandCenter.border": foreground,
      "commandCenter.debuggingBackground": background,
      "commandCenter.foreground": foreground,
      "commandCenter.inactiveBorder": fg_tb,
      "commandCenter.inactiveForeground": inactiveForeground,
      "commentsView.resolvedIcon": fg_tb,
      "commentsView.unresolvedIcon": foreground,
      "contrastActiveBorder": foreground,
      "contrastBorder": "default",
      "debugConsole.errorForeground": foreground,
      "debugConsole.infoForeground": foreground,
      "debugConsole.sourceForeground": foreground,
      "debugConsole.warningForeground": foreground,
      "debugConsoleInputIcon.foreground": foreground,
      "debugExceptionWidget.background": background,
      "debugExceptionWidget.border": fg_ta,
      "debugIcon.breakpointCurrentStackframeForeground": foreground,
      "debugIcon.breakpointDisabledForeground": fg_tb,
      "debugIcon.breakpointForeground": foreground,
      "debugIcon.breakpointStackframeForeground": foreground,
      "debugIcon.breakpointUnverifiedForeground": foreground,
      "debugIcon.continueForeground": foreground,
      "debugIcon.disconnectForeground": foreground,
      "debugIcon.pauseForeground": foreground,
      "debugIcon.restartForeground": foreground,
      "debugIcon.startForeground": foreground,
      "debugIcon.stepBackForeground": foreground,
      "debugIcon.stepIntoForeground": foreground,
      "debugIcon.stepOutForeground": foreground,
      "debugIcon.stepOverForeground": foreground,
      "debugIcon.stopForeground": foreground,
      "debugTokenExpression.boolean": foreground,
      "debugTokenExpression.error": foreground,
      "debugTokenExpression.name": foreground,
      "debugTokenExpression.number": foreground,
      "debugTokenExpression.string": foreground,
      "debugTokenExpression.type": "default",
      "debugTokenExpression.value": foreground,
      "debugToolBar.background": background,
      "debugToolBar.border": fg_ta,
      "debugView.exceptionLabelBackground": background,
      "debugView.exceptionLabelForeground": foreground,
      "debugView.stateLabelBackground": background,
      "debugView.stateLabelForeground": foreground,
      "debugView.valueChangedHighlight": fg_ta,
      "descriptionForeground": foreground,
      "diffEditor.border": fg_ta,
      "diffEditor.diagonalFill": fg_tc,
      "diffEditor.insertedLineBackground": background,
      "diffEditor.insertedTextBackground": fg_tb,
      "diffEditor.insertedTextBorder": "default",
      "diffEditor.move.border": "default",
      "diffEditor.moveActive.border": "default",
      "diffEditor.removedLineBackground": background,
      "diffEditor.removedTextBackground": fg_tb,
      "diffEditor.removedTextBorder": "default",
      "diffEditor.unchangedCodeBackground": background,
      "diffEditor.unchangedRegionBackground": background,
      "diffEditor.unchangedRegionForeground": foreground,
      "diffEditor.unchangedRegionShadow": "default",
      "diffEditorGutter.insertedLineBackground": background,
      "diffEditorGutter.removedLineBackground": background,
      "diffEditorOverview.insertedForeground": foreground,
      "diffEditorOverview.removedForeground": foreground,
      "disabledForeground": foreground,
      "dropdown.background": background,
      "dropdown.border": fg_ta,
      "dropdown.foreground": foreground,
      "dropdown.listBackground": background,
      "editor.background": background,
      "editor.compositionBorder": "default",
      "editor.findMatchBackground": fg_ta,
      "editor.findMatchBorder": fg_ta,
      "editor.findMatchForeground": foreground,
      "editor.findMatchHighlightBackground": fg_tb,
      "editor.findMatchHighlightBorder": fg_ta,
      "editor.findMatchHighlightForeground": foreground,
      "editor.findRangeHighlightBackground": fg_tb,
      "editor.findRangeHighlightBorder": fg_ta,
      "editor.focusedStackFrameHighlightBackground": background,
      "editor.foldBackground": fg_tb,
      "editor.foldPlaceholderForeground": foreground,
      "editor.foreground": foreground,
      "editor.hoverHighlightBackground": fg_tb,
      "editor.inactiveSelectionBackground": fg_tb,
      "editorIndentGuide.activeBackground": activeBackground,
      "editorIndentGuide.background": "default",
      "editor.inlineValuesBackground": background,
      "editor.inlineValuesForeground": foreground,
      "editor.lineHighlightBackground": fg_tc,
      "editor.lineHighlightBorder": "default",
      "editor.linkedEditingBackground": background,
      "editor.placeholder.foreground": foreground,
      "editor.rangeHighlightBackground": fg_tb,
      "editor.rangeHighlightBorder": fg_ta,
      "editor.selectionBackground": fg_tb,
      "editor.selectionForeground": foreground,
      "editor.selectionHighlightBackground": fg_tb,
      "editor.selectionHighlightBorder": fg_ta,
      "editor.snippetFinalTabstopHighlightBackground": background,
      "editor.snippetFinalTabstopHighlightBorder": fg_ta,
      "editor.snippetTabstopHighlightBackground": background,
      "editor.snippetTabstopHighlightBorder": fg_ta,
      "editor.stackFrameHighlightBackground": background,
      "editor.symbolHighlightBackground": fg_tb,
      "editor.symbolHighlightBorder": fg_ta,
      "editor.wordHighlightBackground": fg_tb,
      "editor.wordHighlightBorder": fg_ta,
      "editor.wordHighlightStrongBackground": fg_ta,
      "editor.wordHighlightStrongBorder": fg_ta,
      "editor.wordHighlightTextBackground": background,
      "editor.wordHighlightTextBorder": "default",
      "editorActionList.background": background,
      "editorActionList.focusBackground": background,
      "editorActionList.focusForeground": foreground,
      "editorActionList.foreground": foreground,
      "editorActiveLineNumber.foreground": foreground,
      "editorBracketHighlight.foreground1": "default",
      "editorBracketHighlight.foreground2": "default",
      "editorBracketHighlight.foreground3": "default",
      "editorBracketHighlight.foreground4": "default",
      "editorBracketHighlight.foreground5": "default",
      "editorBracketHighlight.foreground6": "default",
      "editorBracketHighlight.unexpectedBracket.foreground": foreground,
      "editorBracketMatch.background": background,
      "editorBracketMatch.border": fg_ta,
      "editorBracketPairGuide.activeBackground1": "default",
      "editorBracketPairGuide.activeBackground2": "default",
      "editorBracketPairGuide.activeBackground3": "default",
      "editorBracketPairGuide.activeBackground4": "default",
      "editorBracketPairGuide.activeBackground5": "default",
      "editorBracketPairGuide.activeBackground6": "default",
      "editorBracketPairGuide.background1": "default",
      "editorBracketPairGuide.background2": "default",
      "editorBracketPairGuide.background3": "default",
      "editorBracketPairGuide.background4": "default",
      "editorBracketPairGuide.background5": "default",
      "editorBracketPairGuide.background6": "default",
      "editorCodeLens.foreground": foreground,
      "editorCommentsWidget.rangeactiveBackground": activeBackground,
      "editorCommentsWidget.rangeBackground": background,
      "editorCommentsWidget.replyInputBackground": background,
      "editorCommentsWidget.resolvedBorder": "default",
      "editorCommentsWidget.unresolvedBorder": "default",
      "editorCursor.background": background,
      "editorCursor.foreground": foreground,
      "editorError.background": background,
      "editorError.border": fg_ta,
      "editorError.foreground": foreground,
      "editorGhostText.background": background,
      "editorGhostText.border": "default",
      "editorGhostText.foreground": foreground,
      "editorGroup.border": fg_ta,
      "editorGroup.dropBackground": fg_tb,
      "editorGroup.dropIntoPromptBackground": background,
      "editorGroup.dropIntoPromptBorder": "default",
      "editorGroup.dropIntoPromptForeground": foreground,
      "editorGroup.emptyBackground": background,
      "editorGroup.focusedEmptyBorder": fg_ta,
      "editorGroupHeader.border": fg_ta,
      "editorGroupHeader.noTabsBackground": background,
      "editorGroupHeader.tabsBackground": background,
      "editorGroupHeader.tabsBorder": fg_ta,
      "editorGutter.addedBackground": fg_tb,
      "editorGutter.background": background,
      "editorGutter.commentGlyphForeground": foreground,
      "editorGutter.commentRangeForeground": fg_tb,
      "editorGutter.commentUnresolvedGlyphForeground": foreground,
      "editorGutter.deletedBackground": fg_tb,
      "editorGutter.foldingControlForeground": fg_ta,
      "editorGutter.modifiedBackground": fg_tb,
      "editorHint.border": fg_ta,
      "editorHint.foreground": foreground,
      "editorHoverWidget.background": fg_sb,
      "editorHoverWidget.border": fg_ta,
      "editorHoverWidget.foreground": foreground,
      "editorHoverWidget.highlightForeground": foreground,
      "editorHoverWidget.statusBarBackground": fg_tb,
      "editorIndentGuide.activeBackground1": fg_tb,
      "editorIndentGuide.activeBackground2": fg_tb,
      "editorIndentGuide.activeBackground3": fg_tb,
      "editorIndentGuide.activeBackground4": fg_tb,
      "editorIndentGuide.activeBackground5": fg_tb,
      "editorIndentGuide.activeBackground6": fg_tb,
      "editorIndentGuide.background1": fg_tc,
      "editorIndentGuide.background2": fg_tc,
      "editorIndentGuide.background3": fg_tc,
      "editorIndentGuide.background4": fg_tc,
      "editorIndentGuide.background5": fg_tc,
      "editorIndentGuide.background6": fg_tc,
      "editorInfo.background": background,
      "editorInfo.border": fg_ta,
      "editorInfo.foreground": foreground,
      "editorInlayHint.background": background,
      "editorInlayHint.foreground": foreground,
      "editorInlayHint.parameterBackground": background,
      "editorInlayHint.parameterForeground": foreground,
      "editorInlayHint.typeBackground": background,
      "editorInlayHint.typeForeground": foreground,
      "editorLightBulb.foreground": fg_ta,
      "editorLightBulbAi.foreground": foreground,
      "editorLightBulbAutoFix.foreground": fg_ta,
      "editorLineNumber.activeForeground": foreground,
      "editorLineNumber.dimmedForeground": foreground,
      "editorLineNumber.foreground": fg_tb,
      "editorLink.activeForeground": foreground,
      "editorMarkerNavigation.background": fg_tb,
      "editorMarkerNavigationError.background": fg_tb,
      "editorMarkerNavigationError.headerBackground": background,
      "editorMarkerNavigationInfo.background": fg_tb,
      "editorMarkerNavigationInfo.headerBackground": background,
      "editorMarkerNavigationWarning.background": fg_tb,
      "editorMarkerNavigationWarning.headerBackground": background,
      "editorMinimap.inlineChatInserted": "default",
      "editorMultiCursor.primary.background": background,
      "editorMultiCursor.primary.foreground": foreground,
      "editorMultiCursor.secondary.background": background,
      "editorMultiCursor.secondary.foreground": foreground,
      "editorOverviewRuler.addedForeground": fg_tb,
      "editorOverviewRuler.background": background,
      "editorOverviewRuler.border": fg_ta,
      "editorOverviewRuler.bracketMatchForeground": fg_tb,
      "editorOverviewRuler.commentForeground": foreground,
      "editorOverviewRuler.commentUnresolvedForeground": foreground,
      "editorOverviewRuler.commonContentForeground": fg_tb,
      "editorOverviewRuler.currentContentForeground": fg_tb,
      "editorOverviewRuler.deletedForeground": fg_tb,
      "editorOverviewRuler.errorForeground": fg_ta,
      "editorOverviewRuler.findMatchForeground": fg_tb,
      "editorOverviewRuler.incomingContentForeground": fg_tb,
      "editorOverviewRuler.infoForeground": fg_tb,
      "editorOverviewRuler.inlineChatInserted": "default",
      "editorOverviewRuler.inlineChatRemoved": "default",
      "editorOverviewRuler.modifiedForeground": fg_tb,
      "editorOverviewRuler.rangeHighlightForeground": fg_tb,
      "editorOverviewRuler.selectionHighlightForeground": fg_tb,
      "editorOverviewRuler.warningForeground": fg_tb,
      "editorOverviewRuler.wordHighlightForeground": fg_tb,
      "editorOverviewRuler.wordHighlightStrongForeground": fg_tb,
      "editorOverviewRuler.wordHighlightTextForeground": foreground,
      "editorPane.background": fg_tb,
      "editorRuler.foreground": foreground,
      "editorStickyScroll.background": background,
      "editorStickyScroll.border": "default",
      "editorStickyScroll.shadow": "default",
      "editorStickyScrollHover.background": background,
      "editorSuggestWidget.background": background,
      "editorSuggestWidget.border": fg_ta,
      "editorSuggestWidget.focusHighlightForeground": foreground,
      "editorSuggestWidget.foreground": foreground,
      "editorSuggestWidget.highlightForeground": foreground,
      "editorSuggestWidget.selectedBackground": fg_ta,
      "editorSuggestWidget.selectedForeground": foreground,
      "editorSuggestWidget.selectedIconForeground": foreground,
      "editorSuggestWidgetStatus.foreground": foreground,
      "editorUnicodeHighlight.background": background,
      "editorUnicodeHighlight.border": "default",
      "editorUnnecessaryCode.border": fg_ta,
      "editorUnnecessaryCode.opacity": fg_tb,
      "editorWarning.background": background,
      "editorWarning.border": fg_ta,
      "editorWarning.foreground": foreground,
      "editorWatermark.foreground": foreground,
      "editorWhitespace.foreground": fg_tb,
      "editorWidget.background": background,
      "editorWidget.border": fg_ta,
      "editorWidget.foreground": foreground,
      "editorWidget.resizeBorder": fg_ta,
      "errorForeground": foreground,
      "extensionBadge.remoteBackground": background,
      "extensionBadge.remoteForeground": foreground,
      "extensionButton.background": background,
      "extensionButton.foreground": foreground,
      "extensionButton.hoverBackground": background,
      "extensionButton.prominentBackground": background,
      "extensionButton.prominentForeground": foreground,
      "extensionButton.prominentHoverBackground": background,
      "extensionButton.separator": "default",
      "extensionIcon.preReleaseForeground": foreground,
      "extensionIcon.sponsorForeground": foreground,
      "extensionIcon.starForeground": foreground,
      "extensionIcon.verifiedForeground": foreground,
      "focusBorder": fg_ta,
      "foreground": foreground,
      "git.blame.editorDecorationForeground": foreground,
      "gitDecoration.addedResourceForeground": foreground,
      "gitDecoration.conflictingResourceForeground": foreground,
      "gitDecoration.deletedResourceForeground": foreground,
      "gitDecoration.ignoredResourceForeground": fg_ta,
      "gitDecoration.modifiedResourceForeground": foreground,
      "gitDecoration.renamedResourceForeground": foreground,
      "gitDecoration.stageDeletedResourceForeground": foreground,
      "gitDecoration.stageModifiedResourceForeground": foreground,
      "gitDecoration.submoduleResourceForeground": foreground,
      "gitDecoration.untrackedResourceForeground": foreground,
      "icon.foreground": foreground,
      "inlineChat.background": background,
      "inlineChat.border": "default",
      "inlineChat.foreground": foreground,
      "inlineChat.shadow": "default",
      "inlineChatDiff.inserted": "default",
      "inlineChatDiff.removed": "default",
      "inlineChatInput.background": background,
      "inlineChatInput.border": "default",
      "inlineChatInput.focusBorder": "default",
      "inlineChatInput.placeholderForeground": foreground,
      "inlineEdit.gutterIndicator.background": background,
      "inlineEdit.gutterIndicator.primaryBackground": background,
      "inlineEdit.gutterIndicator.primaryForeground": foreground,
      "inlineEdit.gutterIndicator.secondaryBackground": background,
      "inlineEdit.gutterIndicator.secondaryForeground": foreground,
      "inlineEdit.gutterIndicator.successfulBackground": background,
      "inlineEdit.gutterIndicator.successfulForeground": foreground,
      "inlineEdit.indicator.background": background,
      "inlineEdit.indicator.border": "default",
      "inlineEdit.indicator.foreground": foreground,
      "inlineEdit.modifiedBackground": background,
      "inlineEdit.modifiedBorder": "default",
      "inlineEdit.modifiedChangedLineBackground": background,
      "inlineEdit.modifiedChangedTextBackground": background,
      "inlineEdit.originalBackground": background,
      "inlineEdit.originalBorder": "default",
      "inlineEdit.originalChangedLineBackground": background,
      "inlineEdit.originalChangedTextBackground": background,
      "inlineEdit.wordReplacementView.background": background,
      "input.background": background,
      "input.border": fg_ta,
      "input.foreground": foreground,
      "input.placeholderForeground": fg_ta,
      "inputOption.activeBackground": activeBackground,
      "inputOption.activeBorder": fg_ta,
      "inputOption.activeForeground": fg_ta,
      "inputOption.hoverBackground": background,
      "inputValidation.errorBackground": background,
      "inputValidation.errorBorder": fg_ta,
      "inputValidation.errorForeground": foreground,
      "inputValidation.infoBackground": background,
      "inputValidation.infoBorder": fg_ta,
      "inputValidation.infoForeground": foreground,
      "inputValidation.warningBackground": background,
      "inputValidation.warningBorder": fg_ta,
      "inputValidation.warningForeground": foreground,
      "interactive.activeCodeBorder": "default",
      "interactive.inactiveCodeBorder": "default",
      "issues.closed": "default",
      "issues.newIssueDecoration": "default",
      "issues.open": "default",
      "keybindingLabel.background": background,
      "keybindingLabel.border": "default",
      "keybindingLabel.bottomBorder": "default",
      "keybindingLabel.foreground": foreground,
      "keybindingTable.headerBackground": background,
      "keybindingTable.rowsBackground": background,
      "list.activeSelectionBackground": foreground,
      "list.activeSelectionForeground": background,
      "list.activeSelectionIconForeground": foreground,
      "list.deemphasizedForeground": fg_ta,
      "list.dropBackground": fg_tb,
      "list.dropBetweenBackground": background,
      "list.errorForeground": foreground,
      "list.filterMatchBackground": background,
      "list.filterMatchBorder": fg_ta,
      "list.focusAndSelectionOutline": "default",
      "list.focusBackground": fg_ta,
      "list.focusForeground": foreground,
      "list.focusHighlightForeground": foreground,
      "list.focusOutline": "default",
      "list.highlightForeground": foreground,
      "list.hoverBackground": fg_ta,
      "list.hoverForeground": foreground,
      "list.inactiveFocusBackground": fg_tb,
      "list.inactiveFocusOutline": "default",
      "list.inactiveSelectionBackground": fg_tb,
      "list.inactiveSelectionForeground": foreground,
      "list.inactiveSelectionIconForeground": foreground,
      "list.invalidItemForeground": foreground,
      "list.warningForeground": foreground,
      "listFilterWidget.background": background,
      "listFilterWidget.noMatchesOutline": fg_ta,
      "listFilterWidget.outline": foreground,
      "listFilterWidget.shadow": "default",
      "menu.background": background,
      "menu.border": fg_ta,
      "menu.foreground": foreground,
      "menu.selectionBackground": fg_ta,
      "menu.selectionBorder": fg_ta,
      "menu.selectionForeground": background,
      "menu.separatorBackground": fg_ta,
      "menubar.selectionBackground": fg_tb,
      "menubar.selectionBorder": fg_ta,
      "menubar.selectionForeground": foreground,
      "merge.border": fg_ta,
      "merge.commonContentBackground": fg_tb,
      "merge.commonHeaderBackground": fg_tb,
      "merge.currentContentBackground": fg_tb,
      "merge.currentHeaderBackground": fg_tb,
      "merge.incomingContentBackground": fg_tb,
      "merge.incomingHeaderBackground": fg_tb,
      "mergeEditor.change.background": background,
      "mergeEditor.change.word.background": background,
      "mergeEditor.changeBase.background": background,
      "mergeEditor.changeBase.word.background": background,
      "mergeEditor.conflict.handled.minimapOverViewRuler": "default",
      "mergeEditor.conflict.handledFocused.border": "default",
      "mergeEditor.conflict.handledUnfocused.border": "default",
      "mergeEditor.conflict.input1.background": background,
      "mergeEditor.conflict.input2.background": background,
      "mergeEditor.conflict.unhandled.minimapOverViewRuler": "default",
      "mergeEditor.conflict.unhandledFocused.border": "default",
      "mergeEditor.conflict.unhandledUnfocused.border": "default",
      "mergeEditor.conflictingLines.background": background,
      "minimap.background": background,
      "minimap.errorHighlight": fg_ta,
      "minimap.findMatchHighlight": fg_ta,
      "minimap.foregroundOpacity": "default",
      "minimap.infoHighlight": "default",
      "minimap.selectionHighlight": fg_ta,
      "minimap.selectionOccurrenceHighlight": "default",
      "minimap.warningHighlight": fg_ta,
      "minimapGutter.addedBackground": fg_tb,
      "minimapGutter.deletedBackground": fg_tb,
      "minimapGutter.modifiedBackground": fg_tb,
      "minimapSlider.activeBackground": activeBackground,
      "minimapSlider.background": fg_tc,
      "minimapSlider.hoverBackground": fg_tc,
      "multiDiffEditor.background": background,
      "multiDiffEditor.border": "default",
      "multiDiffEditor.headerBackground": background,
      "notebook.cellBorderColor": fg_ta,
      "notebook.cellEditorBackground": background,
      "notebook.cellHoverBackground": background,
      "notebook.cellInsertionIndicator": "default",
      "notebook.cellStatusBarItemHoverBackground": fg_tc,
      "notebook.cellToolbarSeparator": fg_ta,
      "notebook.editorBackground": background,
      "notebook.focusedCellBackground": background,
      "notebook.focusedCellBorder": "default",
      "notebook.focusedEditorBorder": "default",
      "notebook.inactiveFocusedCellBorder": "default",
      "notebook.inactiveSelectedCellBorder": "default",
      "notebook.outputContainerBackgroundColor": background,
      "notebook.outputContainerBorderColor": "default",
      "notebook.selectedCellBackground": background,
      "notebook.selectedCellBorder": "default",
      "notebook.symbolHighlightBackground": background,
      "notebookEditorOverviewRuler.runningCellForeground": foreground,
      "notebookScrollbarSlider.activeBackground": activeBackground,
      "notebookScrollbarSlider.background": background,
      "notebookScrollbarSlider.hoverBackground": background,
      "notebookStatusErrorIcon.foreground": "#ff0000",
      "notebookStatusRunningIcon.foreground": "#ff0000",
      "notebookStatusSuccessIcon.foreground": "#ff0000",
      "notificationCenter.border": fg_ta,
      "notificationCenterHeader.background": background,
      "notificationCenterHeader.foreground": foreground,
      "notificationLink.foreground": foreground,
      "notifications.background": background,
      "notifications.border": fg_ta,
      "notifications.foreground": foreground,
      "notificationsErrorIcon.foreground": foreground,
      "notificationsInfoIcon.foreground": foreground,
      "notificationsWarningIcon.foreground": foreground,
      "notificationToast.border": fg_ta,
      "outputView.background": background,
      "outputViewStickyScroll.background": background,
      "panel.background": background,
      "panel.border": fg_ta,
      "panel.dropBorder": foreground,
      "panelInput.border": fg_ta,
      "panelSection.border": fg_ta,
      "panelSection.dropBackground": fg_tc,
      "panelSectionHeader.background": background,
      "panelSectionHeader.border": fg_ta,
      "panelSectionHeader.foreground": foreground,
      "panelStickyScroll.background": background,
      "panelStickyScroll.border": "default",
      "panelStickyScroll.shadow": "default",
      "panelTitle.activeBorder": fg_ta,
      "panelTitle.activeForeground": foreground,
      "panelTitle.border": "default",
      "panelTitle.inactiveForeground": inactiveForeground,
      "peekView.border": fg_ta,
      "peekViewEditor.background": background,
      "peekViewEditor.matchHighlightBackground": background,
      "peekViewEditor.matchHighlightBorder": fg_ta,
      "peekViewEditorGutter.background": background,
      "peekViewEditorStickyScroll.background": background,
      "peekViewResult.background": background,
      "peekViewResult.fileForeground": foreground,
      "peekViewResult.lineForeground": foreground,
      "peekViewResult.matchHighlightBackground": background,
      "peekViewResult.selectionBackground": background,
      "peekViewResult.selectionForeground": foreground,
      "peekViewTitle.background": background,
      "peekViewTitleDescription.foreground": foreground,
      "peekViewTitleLabel.foreground": foreground,
      "pickerGroup.border": fg_ta,
      "pickerGroup.foreground": foreground,
      "ports.iconRunningProcessForeground": foreground,
      "problemsErrorIcon.foreground": foreground,
      "problemsInfoIcon.foreground": foreground,
      "problemsWarningIcon.foreground": foreground,
      "profileBadge.background": background,
      "profileBadge.foreground": foreground,
      "profiles.sashBorder": "default",
      "progressBar.background": fg_ta,
      "pullRequests.closed": "default",
      "pullRequests.draft": "default",
      "pullRequests.merged": "default",
      "pullRequests.notification": "default",
      "pullRequests.open": "default",
      "quickInput.background": background,
      "quickInput.foreground": foreground,
      "quickInput.list.focusBackground": background,
      "quickInputList.focusBackground": background,
      "quickInputList.focusForeground": foreground,
      "quickInputList.focusIconForeground": foreground,
      "quickInputTitle.background": background,
      "radio.activeBackground": activeBackground,
      "radio.activeBorder": foreground,
      "radio.activeForeground": foreground,
      "radio.inactiveBackground": activeBackground,
      "radio.inactiveBorder": foreground,
      "radio.inactiveForeground": inactiveForeground,
      "radio.inactiveHoverBackground": background,
      "sash.hoverBorder": "default",
      "scmGraph.foreground1": "default",
      "scmGraph.foreground2": "default",
      "scmGraph.foreground3": "default",
      "scmGraph.foreground4": "default",
      "scmGraph.foreground5": "default",
      "scmGraph.historyItemBaseRefColor": "default",
      "scmGraph.historyItemHoverAdditionsForeground": foreground,
      "scmGraph.historyItemHoverDefaultLabelBackground": background,
      "scmGraph.historyItemHoverDefaultLabelForeground": foreground,
      "scmGraph.historyItemHoverDeletionsForeground": foreground,
      "scmGraph.historyItemHoverLabelForeground": foreground,
      "scmGraph.historyItemRefColor": "default",
      "scmGraph.historyItemRemoteRefColor": "default",
      "scrollbar.shadow": fg_tb,
      "scrollbarSlider.activeBackground": activeBackground,
      "scrollbarSlider.background": fg_tb,
      "scrollbarSlider.hoverBackground": fg_tb,
      "search.resultsInfoForeground": foreground,
      "searchEditor.findMatchBackground": background,
      "searchEditor.findMatchBorder": fg_ta,
      "searchEditor.textInputBorder": fg_ta,
      "selection.background": fg_ta,
      "settings.checkboxBackground": background,
      "settings.checkboxBorder": fg_ta,
      "settings.checkboxForeground": foreground,
      "settings.dropdownBackground": background,
      "settings.dropdownBorder": fg_ta,
      "settings.dropdownForeground": foreground,
      "settings.dropdownListBorder": fg_ta,
      "settings.focusedRowBackground": background,
      "settings.focusedRowBorder": "default",
      "settings.headerBorder": "default",
      "settings.headerForeground": foreground,
      "settings.modifiedItemIndicator": fg_ta,
      "settings.numberInputBackground": background,
      "settings.numberInputBorder": fg_ta,
      "settings.numberInputForeground": foreground,
      "settings.rowHoverBackground": background,
      "settings.sashBorder": "default",
      "settings.settingsHeaderHoverForeground": foreground,
      "settings.textInputBackground": background,
      "settings.textInputBorder": fg_ta,
      "settings.textInputForeground": foreground,
      "sideBar.background": background,
      "sideBar.border": fg_ta,
      "sideBar.dropBackground": fg_tb,
      "sideBar.foreground": foreground,
      "sideBarActivityBarTop.border": "default",
      "sideBarSectionHeader.background": fg_tb,
      "sideBarSectionHeader.border": fg_ta,
      "sideBarSectionHeader.foreground": foreground,
      "sideBarStickyScroll.background": background,
      "sideBarStickyScroll.border": "default",
      "sideBarStickyScroll.shadow": "default",
      "sideBarTitle.background": background,
      "sideBarTitle.border": "default",
      "sideBarTitle.foreground": foreground,
      "sideBySideEditor.horizontalBorder": "default",
      "sideBySideEditor.verticalBorder": "default",
      "simpleFindWidget.sashBorder": "default",
      "statusBar.background": fg_tb,
      "statusBar.border": fg_ta,
      "statusBar.debuggingBackground": foreground,
      "statusBar.debuggingBorder": fg_ta,
      "statusBar.debuggingForeground": background,
      "statusBar.focusBorder": "default",
      "statusBar.foreground": foreground,
      "statusBar.noFolderBackground": background,
      "statusBar.noFolderBorder": fg_ta,
      "statusBar.noFolderForeground": foreground,
      "statusBarItem.activeBackground": activeBackground,
      "statusBarItem.compactHoverBackground": background,
      "statusBarItem.errorBackground": background,
      "statusBarItem.errorForeground": foreground,
      "statusBarItem.errorHoverBackground": background,
      "statusBarItem.errorHoverForeground": foreground,
      "statusBarItem.focusBorder": "default",
      "statusBarItem.hoverBackground": background,
      "statusBarItem.hoverForeground": foreground,
      "statusBarItem.offlineBackground": background,
      "statusBarItem.offlineForeground": foreground,
      "statusBarItem.offlineHoverBackground": background,
      "statusBarItem.offlineHoverForeground": foreground,
      "statusBarItem.prominentBackground": background,
      "statusBarItem.prominentForeground": foreground,
      "statusBarItem.prominentHoverBackground": background,
      "statusBarItem.prominentHoverForeground": foreground,
      "statusBarItem.remoteBackground": background,
      "statusBarItem.remoteForeground": foreground,
      "statusBarItem.remoteHoverBackground": background,
      "statusBarItem.remoteHoverForeground": foreground,
      "statusBarItem.warningBackground": background,
      "statusBarItem.warningForeground": foreground,
      "statusBarItem.warningHoverBackground": background,
      "statusBarItem.warningHoverForeground": foreground,
      "symbolIcon.arrayForeground": foreground,
      "symbolIcon.booleanForeground": foreground,
      "symbolIcon.classForeground": foreground,
      "symbolIcon.colorForeground": foreground,
      "symbolIcon.constantForeground": foreground,
      "symbolIcon.constructorForeground": foreground,
      "symbolIcon.enumeratorForeground": foreground,
      "symbolIcon.enumeratorMemberForeground": foreground,
      "symbolIcon.eventForeground": foreground,
      "symbolIcon.fieldForeground": foreground,
      "symbolIcon.fileForeground": foreground,
      "symbolIcon.folderForeground": foreground,
      "symbolIcon.functionForeground": foreground,
      "symbolIcon.interfaceForeground": foreground,
      "symbolIcon.keyForeground": foreground,
      "symbolIcon.keywordForeground": foreground,
      "symbolIcon.methodForeground": foreground,
      "symbolIcon.moduleForeground": foreground,
      "symbolIcon.namespaceForeground": foreground,
      "symbolIcon.nullForeground": foreground,
      "symbolIcon.numberForeground": foreground,
      "symbolIcon.objectForeground": foreground,
      "symbolIcon.operatorForeground": foreground,
      "symbolIcon.packageForeground": foreground,
      "symbolIcon.propertyForeground": foreground,
      "symbolIcon.referenceForeground": foreground,
      "symbolIcon.snippetForeground": foreground,
      "symbolIcon.stringForeground": foreground,
      "symbolIcon.structForeground": foreground,
      "symbolIcon.textForeground": foreground,
      "symbolIcon.typeParameterForeground": foreground,
      "symbolIcon.unitForeground": foreground,
      "symbolIcon.variableForeground": foreground,
      "tab.activeBackground": activeBackground,
      "tab.activeBorder": background,
      "tab.activeBorderTop": background,
      "tab.activeForeground": foreground,
      "tab.activeModifiedBorder": fg_ta,
      "tab.border": background,
      "tab.dragAndDropBorder": "default",
      "tab.hoverBackground": fg_tb,
      "tab.hoverBorder": fg_ta,
      "tab.hoverForeground": fg_ta,
      "tab.inactiveBackground": activeBackground,
      "tab.inactiveForeground": inactiveForeground,
      "tab.inactiveModifiedBorder": background,
      "tab.lastPinnedBorder": "default",
      "tab.selectedBackground": background,
      "tab.selectedBorderTop": "default",
      "tab.selectedForeground": foreground,
      "tab.unfocusedactiveBackground": activeBackground,
      "tab.unfocusedActiveBorder": background,
      "tab.unfocusedActiveBorderTop": background,
      "tab.unfocusedActiveForeground": foreground,
      "tab.unfocusedActiveModifiedBorder": background,
      "tab.unfocusedHoverBackground": fg_tb,
      "tab.unfocusedHoverBorder": background,
      "tab.unfocusedHoverForeground": fg_tb,
      "tab.unfocusedInactiveBackground": activeBackground,
      "tab.unfocusedinactiveForeground": inactiveForeground,
      "tab.unfocusedInactiveModifiedBorder": background,
      "terminal.ansiBlack": foregroundColors.s0,
      "terminal.ansiBlue": foregroundColors.s1,
      "terminal.ansiBrightBlack": foregroundColors.s0,
      "terminal.ansiBrightBlue": foregroundColors.s1,
      "terminal.ansiBrightCyan": foregroundColors.s5,
      "terminal.ansiBrightGreen": foregroundColors.s3,
      "terminal.ansiBrightMagenta": foregroundColors.s2,
      "terminal.ansiBrightRed": foregroundColors.s4,
      "terminal.ansiBrightWhite": foregroundColors.s7,
      "terminal.ansiBrightYellow": foregroundColors.s6,
      "terminal.ansiCyan": foregroundColors.s5,
      "terminal.ansiGreen": foregroundColors.s3,
      "terminal.ansiMagenta": foregroundColors.s2,
      "terminal.ansiRed": foregroundColors.s4,
      "terminal.ansiWhite": foregroundColors.s7,
      "terminal.ansiYellow": foregroundColors.s6,
      "terminal.background": background,
      "terminal.border": fg_ta,
      "terminal.dropBackground": background,
      "terminal.findMatchBackground": background,
      "terminal.findMatchBorder": "default",
      "terminal.findMatchHighlightBackground": background,
      "terminal.findMatchHighlightBorder": "default",
      "terminal.foreground": foreground,
      "terminal.hoverHighlightBackground": background,
      "terminal.inactiveSelectionBackground": background,
      "terminal.initialHintForeground": foreground,
      "terminal.selectionBackground": fg_tb,
      "terminal.selectionForeground": foreground,
      "terminal.tab.activeBorder": foreground,
      "terminalCommandDecoration.defaultBackground": background,
      "terminalCommandDecoration.errorBackground": background,
      "terminalCommandDecoration.successBackground": background,
      "terminalCommandGuide.foreground": foreground,
      "terminalCursor.background": background,
      "terminalCursor.foreground": foreground,
      "terminalOverviewRuler.border": "default",
      "terminalOverviewRuler.cursorForeground": foreground,
      "terminalOverviewRuler.findMatchForeground": foreground,
      "terminalStickyScroll.background": background,
      "terminalStickyScroll.border": "default",
      "terminalStickyScrollHover.background": background,
      "testing.coverCountBadgeBackground": background,
      "testing.coverCountBadgeForeground": foreground,
      "testing.coveredBackground": background,
      "testing.coveredBorder": "default",
      "testing.coveredGutterBackground": background,
      "testing.iconErrored.retired": "default",
      "testing.iconErrored": "default",
      "testing.iconFailed.retired": "default",
      "testing.iconFailed": "default",
      "testing.iconPassed.retired": "default",
      "testing.iconPassed": "default",
      "testing.iconQueued.retired": "default",
      "testing.iconQueued": "default",
      "testing.iconSkipped.retired": "default",
      "testing.iconSkipped": "default",
      "testing.iconUnset.retired": "default",
      "testing.iconUnset": "default",
      "testing.message.error.badgeBackground": background,
      "testing.message.error.badgeBorder": "default",
      "testing.message.error.badgeForeground": foreground,
      "testing.message.error.lineBackground": background,
      "testing.message.info.decorationForeground": foreground,
      "testing.message.info.lineBackground": background,
      "testing.messagePeekBorder": "default",
      "testing.messagePeekHeaderBackground": background,
      "testing.peekBorder": "default",
      "testing.peekHeaderBackground": background,
      "testing.runAction": "default",
      "testing.uncoveredBackground": background,
      "testing.uncoveredBorder": "default",
      "testing.uncoveredBranchBackground": background,
      "testing.uncoveredGutterBackground": background,
      "textBlockQuote.background": background,
      "textBlockQuote.border": fg_ta,
      "textCodeBlock.background": background,
      "textLink.activeForeground": foreground,
      "textLink.foreground": fg_ta,
      "textPreformat.background": background,
      "textPreformat.foreground": foreground,
      "textSeparator.foreground": foreground,
      "titleBar.activeBackground": activeBackground,
      "titleBar.activeForeground": foreground,
      "titleBar.border": fg_ta,
      "titleBar.inactiveBackground": activeBackground,
      "titleBar.inactiveForeground": inactiveForeground,
      "toolbar.activeBackground": activeBackground,
      "toolbar.hoverBackground": background,
      "toolbar.hoverOutline": "default",
      "tree.inactiveIndentGuidesStroke": "default",
      "tree.indentGuidesStroke": fg_ta,
      "tree.tableColumnsBorder": "default",
      "tree.tableOddRowsBackground": background,
      "walkThrough.embeddedEditorBackground": background,
      "walkthrough.stepTitle.foreground": foreground,
      "welcomePage.background": background,
      "welcomePage.buttonBackground": background,
      "welcomePage.buttonHoverBackground": background,
      "welcomePage.progress.background": background,
      "welcomePage.progress.foreground": foreground,
      "welcomePage.tileBackground": background,
      "welcomePage.tileBorder": "default",
      "welcomePage.tileHoverBackground": background,
      "widget.border": "default",
      "widget.shadow": fg_tb,
      "window.activeBorder": fg_ta,
      "window.inactiveBorder": fg_tb,
    },
    tokenColors: [
      {
        scope: ["comment"],
        settings: {
          foreground: fg_tb,
        },
      },
      {
        scope: ["keyword", "storage"],
        settings: {
          foreground: fg_ta,
        },
      },
      {
        scope: ["entity", "strong"],
        settings: {
          fontStyle: "bold",
        },
      },
      {
        scope: ["invalid"],
        settings: {
          foreground: fg_ta,
          fontStyle: "italic underline",
        },
      },
    ],
    "semanticHighlighting": false,
    "semanticTokenColors": {
    }
  };
};

module.exports = {
  opaque,
  opaqueRgb,
  rgbaArrayToStr,
  rgbaStrToArray,
  crtTemplate,
};
